// emit.go — 生成模型 → Go 源码渲染（codegen-conventions.md §2/§3/§4/§5/§6）。
// 生成物仅依赖标准库 + pkg/yang-runtime/object（零 ygot/goyang，YN-05）。
// 全部输入已在 model 层排序，顺序渲染即确定性输出（CG-01）。
package main

import (
	"fmt"
	"go/format"
	"sort"
	"strings"
)

const objectImport = `"github.com/leezesi/usmp/backend/pkg/yang-runtime/object"`

// EmitPackage renders the model into file name → source bytes（gofmt 规范化，
// 非法产物在此报错而非落盘）。splitCount=0 输出单文件 all.gen.go；>0 输出
// structs-0..N-1.go + enum.go/enum_map.go/union.go/registry.go 拆分布局。
func EmitPackage(m *Model, modules []string, splitCount int) (map[string][]byte, error) {
	files, err := emitPackageRaw(m, modules, splitCount)
	if err != nil {
		return nil, err
	}
	for name, src := range files {
		fmted, err := format.Source(src)
		if err != nil {
			return nil, fmt.Errorf("yanggen: 生成物 %s 非法 Go 源（生成器缺陷）: %w", name, err)
		}
		files[name] = fmted
	}
	return files, nil
}

func emitPackageRaw(m *Model, modules []string, splitCount int) (map[string][]byte, error) {
	structSrc := make([]string, 0, len(m.Structs))
	for _, s := range m.Structs {
		src, err := emitStruct(m, s)
		if err != nil {
			return nil, err
		}
		structSrc = append(structSrc, src)
	}

	out := map[string][]byte{}
	if splitCount <= 0 {
		var body strings.Builder
		body.WriteString(emitRegistry(m))
		for _, s := range structSrc {
			body.WriteString(s)
		}
		body.WriteString(emitEnums(m))
		body.WriteString(emitEnumMaps(m))
		body.WriteString(emitUnions(m))
		var b strings.Builder
		b.WriteString(fileHeader(m.Package, modules))
		b.WriteString(importBlock(neededImports(body.String())...))
		b.WriteString(body.String())
		out["all.gen.go"] = []byte(b.String())
		return out, nil
	}

	// 拆分：structs 按类型名字典序（model 已排）ceil(total/N) 均分。
	per := (len(structSrc) + splitCount - 1) / splitCount
	for i := 0; i < splitCount; i++ {
		lo, hi := i*per, (i+1)*per
		if lo > len(structSrc) {
			lo = len(structSrc)
		}
		if hi > len(structSrc) {
			hi = len(structSrc)
		}
		var b strings.Builder
		b.WriteString(fileHeader(m.Package, modules))
		chunk := strings.Join(structSrc[lo:hi], "")
		b.WriteString(importBlock(neededImports(chunk)...))
		b.WriteString(chunk)
		out[fmt.Sprintf("structs-%d.go", i)] = []byte(b.String())
	}
	reg := fileHeader(m.Package, modules) + importBlock("reflect") + emitRegistry(m)
	out["registry.go"] = []byte(reg)
	if len(m.Enums) > 0 {
		out["enum.go"] = []byte(fileHeader(m.Package, modules) + importBlock(objectImport) + emitEnums(m))
		out["enum_map.go"] = []byte(fileHeader(m.Package, modules) + importBlock(objectImport) + emitEnumMaps(m))
	}
	if len(m.Unions) > 0 {
		ub := emitUnions(m)
		out["union.go"] = []byte(fileHeader(m.Package, modules) + importBlock(neededImports(ub)...) + ub)
	}
	return out, nil
}

// neededImports 按 chunk 内容裁剪 import（goimports 语义的最小内建版：
// 生成器可控词表，无需外部工具）。
func neededImports(chunk string) []string {
	var imps []string
	if strings.Contains(chunk, "fmt.") {
		imps = append(imps, "fmt")
	}
	if strings.Contains(chunk, "reflect.") {
		imps = append(imps, "reflect")
	}
	if strings.Contains(chunk, "json.") {
		imps = append(imps, "encoding/json")
	}
	if strings.Contains(chunk, "sort.") {
		imps = append(imps, "sort")
	}
	if strings.Contains(chunk, "strconv.") {
		imps = append(imps, "strconv")
	}
	// 闭集匹配（生成器产出的 object 包引用只有这几种），避免注释文本误报。
	for _, tok := range []string{"object.Empty", "object.Binary", "object.EnumDefinition", "object.EnumLogString",
		"object.RawJSON", "object.JSONArray", "object.StripModule", "object.Parse", "object.EnumValueByName",
		"object.EnumName", "object.EmptyJSON", "object.IsEmptyJSON"} {
		if strings.Contains(chunk, tok) {
			imps = append(imps, objectImport)
			break
		}
	}
	return imps
}

func fileHeader(pkg string, modules []string) string {
	var b strings.Builder
	b.WriteString("// Code generated by yanggen. DO NOT EDIT.\n")
	b.WriteString("// Package " + pkg + " 由 yanggen（retire-ygot-runtime）自 YANG 模型生成：\n")
	for _, m := range modules {
		b.WriteString("//   - " + m + "\n")
	}
	b.WriteString("// 结构约定冻结见 openspec/changes/retire-ygot-runtime/codegen-conventions.md。\n")
	b.WriteString("package " + pkg + "\n\n")
	return b.String()
}

func importBlock(imps ...string) string {
	if len(imps) == 0 {
		return ""
	}
	std, other := []string{}, []string{}
	for _, im := range imps {
		if strings.HasPrefix(im, `"`) {
			other = append(other, im)
		} else {
			std = append(std, `"`+im+`"`)
		}
	}
	sort.Strings(std)
	sort.Strings(other)
	var b strings.Builder
	b.WriteString("import (\n")
	for _, im := range std {
		b.WriteString("\t" + im + "\n")
	}
	if len(std) > 0 && len(other) > 0 {
		b.WriteString("\n")
	}
	for _, im := range other {
		b.WriteString("\t" + im + "\n")
	}
	b.WriteString(")\n\n")
	return b.String()
}

func emitStruct(m *Model, s *Struct) (string, error) {
	var b strings.Builder
	fmt.Fprintf(&b, "// %s represents the %s YANG schema element.\n", s.Name, s.Path)
	fmt.Fprintf(&b, "type %s struct {\n", s.Name)
	for _, f := range s.Fields {
		fmt.Fprintf(&b, "\t%s %s `path:%q module:%q`\n", f.GoName, f.Type, f.YangName, f.Module)
	}
	b.WriteString("}\n\n")

	// 注：勿在注释里写 "object." 字面量——structs 分片的 import 裁剪按词表匹配。
	fmt.Fprintf(&b, "// IsYangObject marks %s as a generated YANG object.\n", s.Name)
	fmt.Fprintf(&b, "func (*%s) IsYangObject() {}\n\n", s.Name)

	if len(s.Keys) > 0 {
		fmt.Fprintf(&b, "// ListKeyMap returns the list keys of %s（YANG 叶名 → 值）。\n", s.Name)
		fmt.Fprintf(&b, "func (t *%s) ListKeyMap() (map[string]interface{}, error) {\n", s.Name)
		for _, k := range s.Keys {
			if k.Ptr {
				fmt.Fprintf(&b, "\tif t.%s == nil {\n\t\treturn nil, fmt.Errorf(\"nil value for key %s\")\n\t}\n", k.GoName, k.GoName)
			}
		}
		b.WriteString("\treturn map[string]interface{}{")
		for i, k := range s.Keys {
			if i > 0 {
				b.WriteString(", ")
			}
			deref := ""
			if k.Ptr {
				deref = "*"
			}
			fmt.Fprintf(&b, "%q: %st.%s", k.YangName, deref, k.GoName)
		}
		b.WriteString("}, nil\n}\n\n")
	}

	if s.OrderedKey != "" {
		om, k := s.Name+"_OrderedMap", s.OrderedKey
		fmt.Fprintf(&b, "// %s is an ordered-by-user list container for %s（字段形状冻结自 ygot）。\n", om, s.Name)
		fmt.Fprintf(&b, "type %s struct {\n\tkeys []%s\n\tvalueMap map[%s]*%s\n}\n\n", om, k, k, s.Name)
		fmt.Fprintf(&b, "func (o *%s) init() {\n\tif o.valueMap == nil {\n\t\to.valueMap = map[%s]*%s{}\n\t}\n}\n\n", om, k, s.Name)
		fmt.Fprintf(&b, "// Keys returns the list keys in insertion order.\nfunc (o *%s) Keys() []%s { return o.keys }\n\n", om, k)
		fmt.Fprintf(&b, "// Values returns the entries in insertion order.\nfunc (o *%s) Values() []*%s {\n\tout := make([]*%s, 0, len(o.keys))\n\tfor _, k := range o.keys {\n\t\tout = append(out, o.valueMap[k])\n\t}\n\treturn out\n}\n\n", om, s.Name, s.Name)
		fmt.Fprintf(&b, "// Len returns the entry count.\nfunc (o *%s) Len() int { return len(o.keys) }\n\n", om)
		fmt.Fprintf(&b, "// Get returns the entry for key k, nil if absent.\nfunc (o *%s) Get(k %s) *%s { return o.valueMap[k] }\n\n", om, k, s.Name)
		fmt.Fprintf(&b, "// Append adds an entry at the end（重复 key 报错）。\nfunc (o *%s) Append(k %s, v *%s) error {\n\to.init()\n\tif _, dup := o.valueMap[k]; dup {\n\t\treturn fmt.Errorf(\"duplicate key %%v\", k)\n\t}\n\to.keys = append(o.keys, k)\n\to.valueMap[k] = v\n\treturn nil\n}\n\n", om, k, s.Name)
	}

	if s.KeyName != "" {
		fmt.Fprintf(&b, "// %s represents the key for list %s of element %s.\n", s.KeyName, s.Name, parentPath(s.Path))
		fmt.Fprintf(&b, "type %s struct {\n", s.KeyName)
		for _, k := range s.Keys {
			fmt.Fprintf(&b, "\t%s %s `path:%q`\n", k.GoName, strings.TrimPrefix(k.Type, "*"), k.YangName)
		}
		b.WriteString("}\n\n")
		fmt.Fprintf(&b, "// ListKeyMap returns the list keys of %s（值接收者，无 nil 面）。\n", s.KeyName)
		fmt.Fprintf(&b, "func (t %s) ListKeyMap() (map[string]interface{}, error) {\n", s.KeyName)
		b.WriteString("\treturn map[string]interface{}{")
		for i, k := range s.Keys {
			if i > 0 {
				b.WriteString(", ")
			}
			fmt.Fprintf(&b, "%q: t.%s", k.YangName, k.GoName)
		}
		b.WriteString("}, nil\n}\n\n")
	}

	b.WriteString(emitJSONMethods(m, s))
	return b.String(), nil
}

func parentPath(p string) string {
	if i := strings.LastIndex(p, "/"); i > 0 {
		return p[:i]
	}
	return p
}

func emitRegistry(m *Model) string {
	var b strings.Builder
	b.WriteString("// Types 是本包全部生成类型的注册表（类型名 → reflect.Type），\n")
	b.WriteString("// 供 Scheme 注册与结构对拍守护测试消费（替代 ygot SchemaTree 的按名索引）。\n")
	b.WriteString("var Types = map[string]reflect.Type{\n")
	for _, s := range m.Structs {
		fmt.Fprintf(&b, "\t%q: reflect.TypeOf((*%s)(nil)).Elem(),\n", s.Name, s.Name)
	}
	b.WriteString("}\n\n")
	return b.String()
}

func emitEnums(m *Model) string {
	var b strings.Builder
	for _, e := range m.Enums {
		bare := strings.TrimPrefix(e.Name, "E_")
		fmt.Fprintf(&b, "// %s is a YANG enumerated type.\n", e.Name)
		fmt.Fprintf(&b, "type %s int64\n\n", e.Name)
		fmt.Fprintf(&b, "// IsYangEnum ensures that %s implements the object.Enum interface.\n", e.Name)
		fmt.Fprintf(&b, "func (%s) IsYangEnum() {}\n\n", e.Name)
		fmt.Fprintf(&b, "// EnumMaps returns the generation-wide enum definition map.\n")
		fmt.Fprintf(&b, "func (e %s) EnumMaps() map[string]map[int64]object.EnumDefinition { return EnumMaps }\n\n", e.Name)
		fmt.Fprintf(&b, "// String renders e as its YANG value name.\n")
		fmt.Fprintf(&b, "func (e %s) String() string {\n\treturn object.EnumLogString(e, int64(e), %q)\n}\n\n", e.Name, e.Name)
		b.WriteString("const (\n")
		fmt.Fprintf(&b, "\t// %s_UNSET corresponds to the value UNSET of %s.\n", bare, e.Name)
		fmt.Fprintf(&b, "\t%s_UNSET %s = 0\n", bare, e.Name)
		for _, v := range e.Values {
			fmt.Fprintf(&b, "\t// %s corresponds to the value %s of %s.\n", v.ConstName, v.RawName, e.Name)
			fmt.Fprintf(&b, "\t%s %s = %d\n", v.ConstName, e.Name, v.Value)
		}
		b.WriteString(")\n\n")
	}
	return b.String()
}

func emitEnumMaps(m *Model) string {
	var b strings.Builder
	b.WriteString("// enumMaps 是全包枚举定义表（外层 key 带 E_ 前缀——消费方按\n")
	b.WriteString("// reflect Type().Name() 查表，失配即静默解码错，勿改口径）。\n")
	b.WriteString("var EnumMaps = map[string]map[int64]object.EnumDefinition{\n")
	for _, e := range m.Enums {
		fmt.Fprintf(&b, "\t%q: {\n", e.Name)
		for _, v := range e.Values {
			if v.DefMod != "" {
				fmt.Fprintf(&b, "\t\t%d: {Name: %q, DefiningModule: %q},\n", v.Value, v.RawName, v.DefMod)
			} else {
				fmt.Fprintf(&b, "\t\t%d: {Name: %q},\n", v.Value, v.RawName)
			}
		}
		b.WriteString("\t},\n")
	}
	b.WriteString("}\n\n")
	return b.String()
}

func emitUnions(m *Model) string {
	var b strings.Builder
	for _, u := range m.Unions {
		fmt.Fprintf(&b, "// %s is a YANG union type.\n", u.Name)
		fmt.Fprintf(&b, "type %s interface {\n\tIs_%s()\n}\n\n", u.Name, u.Name)
		for _, mem := range u.Members {
			wrap := u.Name + "_" + unionMemberSuffix(mem)
			field := unionMemberField(mem)
			fmt.Fprintf(&b, "// %s wraps a %s member of union %s.\n", wrap, mem, u.Name)
			fmt.Fprintf(&b, "type %s struct {\n\t%s %s\n}\n\n", wrap, field, mem)
			fmt.Fprintf(&b, "// Is_%s marks %s as a member of union %s.\n", u.Name, wrap, u.Name)
			fmt.Fprintf(&b, "func (*%s) Is_%s() {}\n\n", wrap, u.Name)
		}
		b.WriteString(emitUnionJSONHelpers(u))
	}
	return b.String()
}

// unionMemberSuffix：成员 Go 类型 → 包装类型后缀（uint16→Uint16、string→String、
// E_X→E_X 原样——冻结自 ygot 生成物形状）。
func unionMemberSuffix(goType string) string {
	if strings.HasPrefix(goType, "E_") || strings.HasPrefix(goType, "object.") {
		return strings.TrimPrefix(goType, "object.")
	}
	return strings.ToUpper(goType[:1]) + goType[1:]
}

// unionMemberField：包装 struct 的唯一字段名 = 成员类型名本身。
func unionMemberField(goType string) string {
	return unionMemberSuffix(goType)
}
