---
apiVersion: biz.usmp.io/v1
kind: BusinessInterface
metadata:
  name: ge0-0-1-access
  labels:
    app: usmp
    environment: demo
spec:
  deviceID: switch-demo-01
  interfaceName: GigabitEthernet0/0/1
  description: 服务器接入端口
  mode: Access
  adminStatus: Up
  accessVlan: 10
  mtu: 1500
  lldpEnabled: true
---
apiVersion: biz.usmp.io/v1
kind: BusinessInterface
metadata:
  name: ge0-0-2-trunk
  labels:
    app: usmp
    environment: demo
spec:
  deviceID: switch-demo-01
  interfaceName: GigabitEthernet0/0/2
  description: 交换机级联端口
  mode: Trunk
  adminStatus: Up
  nativeVlan: 1
  trunkAllowedVlans:
    - vlanID: 10
      isNative: false
    - vlanID: 20
      isNative: false
    - vlanID: 30
      isNative: false
    - vlanID: 99
      isNative: true
  mtu: 9216
  speed: 1000
  duplex: full
---
apiVersion: biz.usmp.io/v1
kind: BusinessInterface
metadata:
  name: vlanif10-l3
  labels:
    app: usmp
    environment: demo
spec:
  deviceID: switch-demo-01
  interfaceName: Vlanif10
  description: VLAN 10 三层网关
  mode: L3
  adminStatus: Up
  ipAddress: 192.168.10.1
  netmask: 255.255.255.0
  mtu: 1500
