/*
Package businessdemo is a generated package which contains definitions
of structs which represent a YANG schema. The generated schema can be
compressed by a series of transformations (compression was false
in this case).

This package was generated by github.com/openconfig/ygot@v0.29.20/genutil/names.go
using the following YANG input files:
  - usmp-business-vlan-net

Imported modules were sourced from:
  - ../../backend/internal/yang/models/...
*/
package businessdemo

import (
	"encoding/json"
	"fmt"
	"reflect"

	"github.com/openconfig/goyang/pkg/yang"
	"github.com/openconfig/ygot/ygot"
	"github.com/openconfig/ygot/ytypes"
)

// Binary is a type that is used for fields that have a YANG type of
// binary. It is used such that binary fields can be distinguished from
// leaf-lists of uint8s (which are mapped to []uint8, equivalent to
// []byte in reflection).
type Binary []byte

// YANGEmpty is a type that is used for fields that have a YANG type of
// empty. It is used such that empty fields can be distinguished from boolean fields
// in the generated code.
type YANGEmpty bool

var (
	SchemaTree map[string]*yang.Entry
	ΛEnumTypes map[string][]reflect.Type
)

func init() {
	var err error
	initΛEnumTypes()
	if SchemaTree, err = UnzipSchema(); err != nil {
		panic("schema error: " + err.Error())
	}
}

// Schema returns the details of the generated schema.
func Schema() (*ytypes.Schema, error) {
	uzp, err := UnzipSchema()
	if err != nil {
		return nil, fmt.Errorf("cannot unzip schema, %v", err)
	}

	return &ytypes.Schema{
		Root:       &Device{},
		SchemaTree: uzp,
		Unmarshal:  Unmarshal,
	}, nil
}

// UnzipSchema unzips the zipped schema and returns a map of yang.Entry nodes,
// keyed by the name of the struct that the yang.Entry describes the schema for.
func UnzipSchema() (map[string]*yang.Entry, error) {
	var schemaTree map[string]*yang.Entry
	var err error
	if schemaTree, err = ygot.GzipToSchema(ySchema); err != nil {
		return nil, fmt.Errorf("could not unzip the schema; %v", err)
	}
	return schemaTree, nil
}

// Unmarshal unmarshals data, which must be RFC7951 JSON format, into
// destStruct, which must be non-nil and the correct GoStruct type. It returns
// an error if the destStruct is not found in the schema or the data cannot be
// unmarshaled. The supplied options (opts) are used to control the behaviour
// of the unmarshal function - for example, determining whether errors are
// thrown for unknown fields in the input JSON.
func Unmarshal(data []byte, destStruct ygot.GoStruct, opts ...ytypes.UnmarshalOpt) error {
	tn := reflect.TypeOf(destStruct).Elem().Name()
	schema, ok := SchemaTree[tn]
	if !ok {
		return fmt.Errorf("could not find schema for type %s", tn)
	}
	var jsonTree interface{}
	if err := json.Unmarshal([]byte(data), &jsonTree); err != nil {
		return err
	}
	return ytypes.Unmarshal(schema, destStruct, jsonTree, opts...)
}

// Device represents the /device YANG schema element.
type Device struct {
	BusinessVlanNet *UsmpBusinessVlanNet_BusinessVlanNet `path:"business-vlan-net" module:"usmp-business-vlan-net"`
}

// IsYANGGoStruct ensures that Device implements the yang.GoStruct
// interface. This allows functions that need to handle this struct to
// identify it as being generated by ygen.
func (*Device) IsYANGGoStruct() {}

// Validate validates s against the YANG schema corresponding to its type.
func (t *Device) ΛValidate(opts ...ygot.ValidationOption) error {
	if err := ytypes.Validate(SchemaTree["Device"], t, opts...); err != nil {
		return err
	}
	return nil
}

// Validate validates s against the YANG schema corresponding to its type.
func (t *Device) Validate(opts ...ygot.ValidationOption) error {
	return t.ΛValidate(opts...)
}

// ΛEnumTypeMap returns a map, keyed by YANG schema path, of the enumerated types
// that are included in the generated code.
func (t *Device) ΛEnumTypeMap() map[string][]reflect.Type { return ΛEnumTypes }

// ΛBelongingModule returns the name of the module that defines the namespace
// of Device.
func (*Device) ΛBelongingModule() string {
	return ""
}

// UsmpBusinessVlanNet_BusinessVlanNet represents the /usmp-business-vlan-net/business-vlan-net YANG schema element.
type UsmpBusinessVlanNet_BusinessVlanNet struct {
	Description *string                                                 `path:"description" module:"usmp-business-vlan-net"`
	Devices     map[string]*UsmpBusinessVlanNet_BusinessVlanNet_Devices `path:"devices" module:"usmp-business-vlan-net"`
	Enabled     *bool                                                   `path:"enabled" module:"usmp-business-vlan-net"`
	Name        *string                                                 `path:"name" module:"usmp-business-vlan-net"`
	Qos         *UsmpBusinessVlanNet_BusinessVlanNet_Qos                `path:"qos" module:"usmp-business-vlan-net"`
	VlanId      *uint16                                                 `path:"vlan-id" module:"usmp-business-vlan-net"`
	VlanType    E_UsmpBusinessVlanNet_BusinessVlanNet_VlanType          `path:"vlan-type" module:"usmp-business-vlan-net"`
}

// IsYANGGoStruct ensures that UsmpBusinessVlanNet_BusinessVlanNet implements the yang.GoStruct
// interface. This allows functions that need to handle this struct to
// identify it as being generated by ygen.
func (*UsmpBusinessVlanNet_BusinessVlanNet) IsYANGGoStruct() {}

// NewDevices creates a new entry in the Devices list of the
// UsmpBusinessVlanNet_BusinessVlanNet struct. The keys of the list are populated from the input
// arguments.
func (t *UsmpBusinessVlanNet_BusinessVlanNet) NewDevices(Ip string) (*UsmpBusinessVlanNet_BusinessVlanNet_Devices, error) {

	// Initialise the list within the receiver struct if it has not already been
	// created.
	if t.Devices == nil {
		t.Devices = make(map[string]*UsmpBusinessVlanNet_BusinessVlanNet_Devices)
	}

	key := Ip

	// Ensure that this key has not already been used in the
	// list. Keyed YANG lists do not allow duplicate keys to
	// be created.
	if _, ok := t.Devices[key]; ok {
		return nil, fmt.Errorf("duplicate key %v for list Devices", key)
	}

	t.Devices[key] = &UsmpBusinessVlanNet_BusinessVlanNet_Devices{
		Ip: &Ip,
	}

	return t.Devices[key], nil
}

// Validate validates s against the YANG schema corresponding to its type.
func (t *UsmpBusinessVlanNet_BusinessVlanNet) ΛValidate(opts ...ygot.ValidationOption) error {
	if err := ytypes.Validate(SchemaTree["UsmpBusinessVlanNet_BusinessVlanNet"], t, opts...); err != nil {
		return err
	}
	return nil
}

// Validate validates s against the YANG schema corresponding to its type.
func (t *UsmpBusinessVlanNet_BusinessVlanNet) Validate(opts ...ygot.ValidationOption) error {
	return t.ΛValidate(opts...)
}

// ΛEnumTypeMap returns a map, keyed by YANG schema path, of the enumerated types
// that are included in the generated code.
func (t *UsmpBusinessVlanNet_BusinessVlanNet) ΛEnumTypeMap() map[string][]reflect.Type {
	return ΛEnumTypes
}

// ΛBelongingModule returns the name of the module that defines the namespace
// of UsmpBusinessVlanNet_BusinessVlanNet.
func (*UsmpBusinessVlanNet_BusinessVlanNet) ΛBelongingModule() string {
	return "usmp-business-vlan-net"
}

// UsmpBusinessVlanNet_BusinessVlanNet_Devices represents the /usmp-business-vlan-net/business-vlan-net/devices YANG schema element.
type UsmpBusinessVlanNet_BusinessVlanNet_Devices struct {
	AccessPorts []string `path:"access-ports" module:"usmp-business-vlan-net"`
	Ip          *string  `path:"ip" module:"usmp-business-vlan-net"`
	TrunkPorts  []string `path:"trunk-ports" module:"usmp-business-vlan-net"`
}

// IsYANGGoStruct ensures that UsmpBusinessVlanNet_BusinessVlanNet_Devices implements the yang.GoStruct
// interface. This allows functions that need to handle this struct to
// identify it as being generated by ygen.
func (*UsmpBusinessVlanNet_BusinessVlanNet_Devices) IsYANGGoStruct() {}

// ΛListKeyMap returns the keys of the UsmpBusinessVlanNet_BusinessVlanNet_Devices struct, which is a YANG list entry.
func (t *UsmpBusinessVlanNet_BusinessVlanNet_Devices) ΛListKeyMap() (map[string]interface{}, error) {
	if t.Ip == nil {
		return nil, fmt.Errorf("nil value for key Ip")
	}

	return map[string]interface{}{
		"ip": *t.Ip,
	}, nil
}

// Validate validates s against the YANG schema corresponding to its type.
func (t *UsmpBusinessVlanNet_BusinessVlanNet_Devices) ΛValidate(opts ...ygot.ValidationOption) error {
	if err := ytypes.Validate(SchemaTree["UsmpBusinessVlanNet_BusinessVlanNet_Devices"], t, opts...); err != nil {
		return err
	}
	return nil
}

// Validate validates s against the YANG schema corresponding to its type.
func (t *UsmpBusinessVlanNet_BusinessVlanNet_Devices) Validate(opts ...ygot.ValidationOption) error {
	return t.ΛValidate(opts...)
}

// ΛEnumTypeMap returns a map, keyed by YANG schema path, of the enumerated types
// that are included in the generated code.
func (t *UsmpBusinessVlanNet_BusinessVlanNet_Devices) ΛEnumTypeMap() map[string][]reflect.Type {
	return ΛEnumTypes
}

// ΛBelongingModule returns the name of the module that defines the namespace
// of UsmpBusinessVlanNet_BusinessVlanNet_Devices.
func (*UsmpBusinessVlanNet_BusinessVlanNet_Devices) ΛBelongingModule() string {
	return "usmp-business-vlan-net"
}

// UsmpBusinessVlanNet_BusinessVlanNet_Qos represents the /usmp-business-vlan-net/business-vlan-net/qos YANG schema element.
type UsmpBusinessVlanNet_BusinessVlanNet_Qos struct {
	Priority *uint8 `path:"priority" module:"usmp-business-vlan-net"`
}

// IsYANGGoStruct ensures that UsmpBusinessVlanNet_BusinessVlanNet_Qos implements the yang.GoStruct
// interface. This allows functions that need to handle this struct to
// identify it as being generated by ygen.
func (*UsmpBusinessVlanNet_BusinessVlanNet_Qos) IsYANGGoStruct() {}

// Validate validates s against the YANG schema corresponding to its type.
func (t *UsmpBusinessVlanNet_BusinessVlanNet_Qos) ΛValidate(opts ...ygot.ValidationOption) error {
	if err := ytypes.Validate(SchemaTree["UsmpBusinessVlanNet_BusinessVlanNet_Qos"], t, opts...); err != nil {
		return err
	}
	return nil
}

// Validate validates s against the YANG schema corresponding to its type.
func (t *UsmpBusinessVlanNet_BusinessVlanNet_Qos) Validate(opts ...ygot.ValidationOption) error {
	return t.ΛValidate(opts...)
}

// ΛEnumTypeMap returns a map, keyed by YANG schema path, of the enumerated types
// that are included in the generated code.
func (t *UsmpBusinessVlanNet_BusinessVlanNet_Qos) ΛEnumTypeMap() map[string][]reflect.Type {
	return ΛEnumTypes
}

// ΛBelongingModule returns the name of the module that defines the namespace
// of UsmpBusinessVlanNet_BusinessVlanNet_Qos.
func (*UsmpBusinessVlanNet_BusinessVlanNet_Qos) ΛBelongingModule() string {
	return "usmp-business-vlan-net"
}

// E_UsmpBusinessVlanNet_BusinessVlanNet_VlanType is a derived int64 type which is used to represent
// the enumerated node UsmpBusinessVlanNet_BusinessVlanNet_VlanType. An additional value named
// UsmpBusinessVlanNet_BusinessVlanNet_VlanType_UNSET is added to the enumeration which is used as
// the nil value, indicating that the enumeration was not explicitly set by
// the program importing the generated structures.
type E_UsmpBusinessVlanNet_BusinessVlanNet_VlanType int64

// IsYANGGoEnum ensures that UsmpBusinessVlanNet_BusinessVlanNet_VlanType implements the yang.GoEnum
// interface. This ensures that UsmpBusinessVlanNet_BusinessVlanNet_VlanType can be identified as a
// mapped type for a YANG enumeration.
func (E_UsmpBusinessVlanNet_BusinessVlanNet_VlanType) IsYANGGoEnum() {}

// ΛMap returns the value lookup map associated with  UsmpBusinessVlanNet_BusinessVlanNet_VlanType.
func (E_UsmpBusinessVlanNet_BusinessVlanNet_VlanType) ΛMap() map[string]map[int64]ygot.EnumDefinition {
	return ΛEnum
}

// String returns a logging-friendly string for E_UsmpBusinessVlanNet_BusinessVlanNet_VlanType.
func (e E_UsmpBusinessVlanNet_BusinessVlanNet_VlanType) String() string {
	return ygot.EnumLogString(e, int64(e), "E_UsmpBusinessVlanNet_BusinessVlanNet_VlanType")
}

const (
	// UsmpBusinessVlanNet_BusinessVlanNet_VlanType_UNSET corresponds to the value UNSET of UsmpBusinessVlanNet_BusinessVlanNet_VlanType
	UsmpBusinessVlanNet_BusinessVlanNet_VlanType_UNSET E_UsmpBusinessVlanNet_BusinessVlanNet_VlanType = 0
	// UsmpBusinessVlanNet_BusinessVlanNet_VlanType_common corresponds to the value common of UsmpBusinessVlanNet_BusinessVlanNet_VlanType
	UsmpBusinessVlanNet_BusinessVlanNet_VlanType_common E_UsmpBusinessVlanNet_BusinessVlanNet_VlanType = 1
	// UsmpBusinessVlanNet_BusinessVlanNet_VlanType_super corresponds to the value super of UsmpBusinessVlanNet_BusinessVlanNet_VlanType
	UsmpBusinessVlanNet_BusinessVlanNet_VlanType_super E_UsmpBusinessVlanNet_BusinessVlanNet_VlanType = 2
)

// ΛEnum is a map, keyed by the name of the type defined for each enum in the
// generated Go code, which provides a mapping between the constant int64 value
// of each value of the enumeration, and the string that is used to represent it
// in the YANG schema. The map is named ΛEnum in order to avoid clash with any
// valid YANG identifier.
var ΛEnum = map[string]map[int64]ygot.EnumDefinition{
	"E_UsmpBusinessVlanNet_BusinessVlanNet_VlanType": {
		1: {Name: "common"},
		2: {Name: "super"},
	},
}

var (
	// ySchema is a byte slice contain a gzip compressed representation of the
	// YANG schema from which the Go code was generated. When uncompressed the
	// contents of the byte slice is a JSON document containing an object, keyed
	// on the name of the generated struct, and containing the JSON marshalled
	// contents of a goyang yang.Entry struct, which defines the schema for the
	// fields within the struct.
	ySchema = []byte{
		0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x57, 0x5b, 0x4f, 0xdb, 0x4c,
		0x10, 0xfd, 0x2f, 0xf3, 0xf4, 0x7d, 0xd2, 0x1a, 0x6c, 0xe5, 0x46, 0xfc, 0x06, 0x0d, 0xa8, 0x15,
		0x85, 0xb6, 0xdc, 0x1e, 0x1a, 0x10, 0xda, 0xd8, 0x43, 0x58, 0x61, 0xef, 0xba, 0x7b, 0x49, 0x49,
		0x23, 0xff, 0xf7, 0x6a, 0xd7, 0xeb, 0xc4, 0x81, 0x00, 0x82, 0x42, 0x94, 0x27, 0x60, 0x7d, 0x66,
		0xe6, 0xf8, 0x9c, 0x99, 0x59, 0x33, 0x83, 0x5d, 0xce, 0x85, 0xa6, 0x9a, 0x09, 0x0e, 0xf1, 0x0c,
		0x98, 0x3a, 0xa0, 0x77, 0x78, 0x22, 0x84, 0x86, 0x58, 0x4b, 0x83, 0x04, 0x54, 0x72, 0x8b, 0x39,
		0x2d, 0xa8, 0xbe, 0x85, 0x18, 0xb6, 0x81, 0x80, 0xd2, 0xd2, 0x24, 0x9a, 0xd3, 0x1c, 0x21, 0x86,
		0x01, 0x4e, 0x58, 0x82, 0x50, 0x12, 0xf8, 0x24, 0xf8, 0x0d, 0x1b, 0x43, 0x1c, 0x12, 0x18, 0x30,
		0x69, 0x73, 0x8d, 0x8c, 0x62, 0x1c, 0x95, 0x0a, 0x26, 0x19, 0xe5, 0x01, 0x47, 0x6d, 0x0f, 0x97,
		0xcb, 0x2d, 0x27, 0x37, 0x2a, 0x2f, 0x82, 0x47, 0x51, 0xdb, 0x8f, 0xf3, 0x3c, 0x20, 0x71, 0xae,
		0xf2, 0x62, 0xcf, 0x83, 0x2e, 0x32, 0xca, 0x8f, 0x51, 0x5f, 0x3f, 0xf8, 0x7b, 0x35, 0xc3, 0x14,
		0x55, 0x22, 0x59, 0x51, 0xb3, 0x69, 0x00, 0x0e, 0x19, 0x4f, 0xdd, 0x2f, 0xc7, 0x55, 0x89, 0x26,
		0x92, 0xc0, 0x77, 0x89, 0x37, 0xec, 0xde, 0x86, 0xf8, 0xc7, 0x66, 0x34, 0xb1, 0xe7, 0xa7, 0xc2,
		0xc8, 0x04, 0xdd, 0x6b, 0xca, 0xb1, 0xc9, 0x91, 0xeb, 0xc5, 0xb3, 0xcf, 0x54, 0x2d, 0x0e, 0x2b,
		0x69, 0x0f, 0x71, 0xfa, 0x5b, 0xc8, 0x14, 0x62, 0x28, 0xaa, 0x84, 0x65, 0x49, 0xe0, 0x6c, 0x5a,
		0xb8, 0x0c, 0x15, 0x83, 0x68, 0x67, 0x4e, 0x41, 0x69, 0xc9, 0xf8, 0xd8, 0x56, 0xa7, 0x5a, 0xa3,
		0xe4, 0x10, 0x0f, 0x61, 0x6b, 0x16, 0x91, 0x9d, 0xb0, 0x84, 0x2b, 0x1b, 0x99, 0x3a, 0x2f, 0xd4,
		0x7b, 0xa9, 0xbc, 0x5d, 0xe7, 0x7b, 0xbd, 0xda, 0xd7, 0x03, 0x1f, 0xba, 0x52, 0x75, 0x9a, 0x24,
		0xb6, 0x4e, 0x21, 0xa4, 0x56, 0x4f, 0xc9, 0xfe, 0x95, 0x29, 0xbd, 0xab, 0xb5, 0xc3, 0x1f, 0xd1,
		0xfb, 0xfd, 0x0c, 0xad, 0x70, 0xca, 0x0a, 0xd2, 0x6e, 0x77, 0x7b, 0xed, 0x76, 0xd8, 0x6b, 0xf5,
		0xc2, 0x7e, 0xa7, 0x13, 0x75, 0xa3, 0x0e, 0x81, 0x23, 0xc6, 0x17, 0x90, 0x90, 0xc0, 0x37, 0x99,
		0xa2, 0xc4, 0x74, 0x6f, 0x0a, 0x31, 0x37, 0x59, 0xd6, 0x38, 0x38, 0x57, 0x28, 0x21, 0xbe, 0xa1,
		0x99, 0xc2, 0x72, 0x2e, 0xed, 0x12, 0xa3, 0x0d, 0xb3, 0xb7, 0xdb, 0xf2, 0xf6, 0xb2, 0xe2, 0x85,
		0x1e, 0x65, 0xc5, 0x26, 0x71, 0xff, 0x6f, 0x18, 0x06, 0xfd, 0xab, 0x59, 0x44, 0x5a, 0xe5, 0xe5,
		0xe5, 0xd6, 0xff, 0xb3, 0x56, 0xb9, 0x38, 0xa8, 0x5e, 0x48, 0x4b, 0xc3, 0xef, 0x36, 0xa9, 0x0d,
		0x9a, 0x84, 0x36, 0xb3, 0x0b, 0x4a, 0x97, 0xaf, 0xf6, 0xda, 0x47, 0xaf, 0x5b, 0xa6, 0xc5, 0x5e,
		0xf8, 0x38, 0x89, 0x4a, 0x02, 0xc8, 0xe9, 0x28, 0xc3, 0xf4, 0x85, 0xa6, 0xaf, 0x51, 0x6b, 0xf5,
		0x2b, 0x9a, 0x97, 0x1f, 0x09, 0x91, 0x21, 0xe5, 0x0e, 0x54, 0xed, 0xc7, 0x67, 0xd9, 0x3a, 0xc8,
		0x06, 0xb5, 0xd6, 0x70, 0x37, 0xf8, 0x49, 0x83, 0x3f, 0x61, 0xd0, 0xbf, 0x0e, 0xdc, 0x68, 0x46,
		0x7e, 0x36, 0x7f, 0x89, 0xf7, 0xbb, 0x47, 0x6c, 0xae, 0x37, 0xdc, 0x21, 0x3f, 0xc4, 0x13, 0xf7,
		0x47, 0x21, 0x99, 0x90, 0x4c, 0x4f, 0x5f, 0xd0, 0x7a, 0x0e, 0x5b, 0xa7, 0xde, 0x9d, 0x79, 0x79,
		0xc3, 0xb8, 0xde, 0x01, 0x02, 0x27, 0x94, 0x8f, 0x11, 0xe2, 0xa1, 0x9b, 0x4c, 0x0b, 0x3c, 0x90,
		0x34, 0xb1, 0x8a, 0x0e, 0xd8, 0x98, 0xf9, 0x01, 0x3c, 0xc6, 0x31, 0xd5, 0x6c, 0x82, 0x7e, 0xd4,
		0x08, 0x5c, 0xd0, 0xcc, 0x20, 0xc4, 0xbd, 0xd2, 0x0d, 0xeb, 0x2b, 0xa3, 0xc2, 0xb2, 0xf4, 0xab,
		0xa2, 0xde, 0x0f, 0x9e, 0x52, 0x65, 0xc4, 0x87, 0x0e, 0xad, 0x33, 0x9d, 0x3d, 0x39, 0xb4, 0x47,
		0x94, 0xa7, 0x54, 0x0b, 0x39, 0x6d, 0xd2, 0xaa, 0x63, 0xd6, 0xe9, 0x53, 0x77, 0xc9, 0xa7, 0xa8,
		0xfb, 0x8f, 0x46, 0xb5, 0xc3, 0x7e, 0xfb, 0x4d, 0x5e, 0x45, 0xce, 0x2b, 0xaf, 0x9b, 0xf6, 0x14,
		0x9f, 0x69, 0xea, 0x05, 0x6e, 0x3d, 0x6a, 0xed, 0x73, 0x93, 0xdb, 0x9f, 0x67, 0xe2, 0x0b, 0x77,
		0xdf, 0xef, 0x89, 0xc8, 0x73, 0xbb, 0x0d, 0x42, 0x02, 0xca, 0x14, 0xf6, 0x76, 0x88, 0x2c, 0x5c,
		0x9c, 0x56, 0xdb, 0x25, 0x9e, 0x41, 0x08, 0x71, 0x8d, 0x22, 0x10, 0xd9, 0xc5, 0xe3, 0x70, 0x8d,
		0x86, 0x6c, 0x37, 0xb6, 0xb7, 0xc9, 0x51, 0x56, 0x0b, 0x66, 0x65, 0xcb, 0xae, 0xfa, 0xf6, 0xff,
		0xc0, 0x06, 0x5e, 0xc1, 0x20, 0xf5, 0xff, 0xe1, 0xfc, 0x0d, 0x00, 0x00, 0xff, 0xff, 0x97, 0x1f,
		0x08, 0xe5, 0x2a, 0x0d, 0x00, 0x00,
	}
)

// ΛEnumTypes is a map, keyed by a YANG schema path, of the enumerated types that
// correspond with the leaf. The type is represented as a reflect.Type. The naming
// of the map ensures that there are no clashes with valid YANG identifiers.
func initΛEnumTypes() {
	ΛEnumTypes = map[string][]reflect.Type{
		"/business-vlan-net/vlan-type": []reflect.Type{
			reflect.TypeOf((E_UsmpBusinessVlanNet_BusinessVlanNet_VlanType)(0)),
		},
	}
}
