// Command blacklistgen generates a Go set of blacklisted module names from an
// SND package blacklist.xml (CN-03). An entry is emitted only when the
// blacklisted revision matches the module's latest revision in the given YANG
// source directory — revision matching is a build-time fact, so runtime keeps
// a plain name set with zero snd-file dependency. Output is committed and
// guarded by the R04 regen-and-diff gate, mirroring tasknamegen.
package main

import (
	"encoding/xml"
	"flag"
	"fmt"
	"go/format"
	"log"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"

	"github.com/openconfig/goyang/pkg/yang"
)

type blacklist struct {
	Modules []struct {
		Name     string `xml:"name"`
		Revision string `xml:"revision"`
	} `xml:"module"`
}

var revisionRe = regexp.MustCompile(`(?m)^\s*revision\s+"?(\d{4}-\d{2}-\d{2})"?\s*[{;]`)

// latestRevision extracts the newest revision statement from a .yang file.
func latestRevision(path string) (string, error) {
	b, err := os.ReadFile(path)
	if err != nil {
		return "", err
	}
	best := ""
	for _, m := range revisionRe.FindAllStringSubmatch(string(b), -1) {
		if m[1] > best {
			best = m[1]
		}
	}
	if best == "" {
		return "", fmt.Errorf("no revision statement in %s", path)
	}
	return best, nil
}

func main() {
	blPath := flag.String("blacklist", "", "path to blacklist.xml")
	yangDir := flag.String("path", "", "YANG source directory (revision verification)")
	output := flag.String("output", "", "output .go file")
	pkg := flag.String("package", "yangschema", "output package name")
	flag.Parse()
	if *blPath == "" || *yangDir == "" || *output == "" {
		log.Fatal("blacklistgen: -blacklist, -path and -output are required")
	}

	names, err := collectBlacklistedRoots(*blPath, *yangDir)
	if err != nil {
		log.Fatalf("blacklistgen: %v", err)
	}
	emit(names, *pkg, *output)
}

// collectBlacklistedRoots parses blacklist.xml and returns the sorted set of
// top-level data-container names of revision-matched blacklisted modules.
func collectBlacklistedRoots(blPath, yangDir string) ([]string, error) {
	raw, err := os.ReadFile(blPath)
	if err != nil {
		return nil, fmt.Errorf("read blacklist: %w", err)
	}
	var bl blacklist
	if err := xml.Unmarshal(raw, &bl); err != nil {
		return nil, fmt.Errorf("parse blacklist: %w", err)
	}

	ms := yang.NewModules()
	ms.AddPath(yangDir)

	// 键 = 模块顶层数据容器名（与 /yang/modules 的模块键同一命名域，tasknamegen 同法）。
	rootSet := map[string]bool{}
	for _, m := range bl.Modules {
		yf := filepath.Join(yangDir, m.Name+".yang")
		rev, err := latestRevision(yf)
		if err != nil {
			// 模块文件不在包内（如 huawei-evc）：黑名单条目无对应模型，跳过。
			log.Printf("blacklistgen: skip %s (%v)", m.Name, err)
			continue
		}
		if rev != m.Revision {
			// revision 不匹配：黑名单针对的是另一版本，运行集不受影响。
			log.Printf("blacklistgen: skip %s (blacklist rev %s != source rev %s)", m.Name, m.Revision, rev)
			continue
		}
		if err := ms.Read(yf); err != nil {
			log.Printf("blacklistgen: skip %s (read: %v)", m.Name, err)
			continue
		}
	}
	if errs := ms.Process(); len(errs) > 0 {
		// 注解型能力：解析告警不阻断生成（R08），仅记录。
		for _, e := range errs {
			log.Printf("blacklistgen: yang process warning: %v", e)
		}
	}
	for _, m := range bl.Modules {
		mod, ok := ms.Modules[m.Name]
		if !ok || mod == nil {
			continue
		}
		e := yang.ToEntry(mod)
		if e == nil {
			continue
		}
		for name, child := range e.Dir {
			if child != nil && child.Dir != nil && child.RPC == nil {
				rootSet[name] = true
			}
		}
	}
	names := make([]string, 0, len(rootSet))
	for n := range rootSet {
		names = append(names, n)
	}
	sort.Strings(names)

	return names, nil
}

func emit(names []string, pkg string, output string) {
	var b strings.Builder
	fmt.Fprintf(&b, `// Code generated by tools/blacklistgen. DO NOT EDIT.
//
// Blacklisted module names from the SND package blacklist.xml whose revision
// matches the in-repo YANG source (CN-03). Annotation only — never used to
// prune the module set.

package %s

// BlacklistedModules is the set of top-level container names of SND-blacklisted
// modules (keyed like /yang/modules module names, e.g. "system"),
// revision-matched at generation time.
var BlacklistedModules = map[string]bool{
`, pkg)
	for _, n := range names {
		fmt.Fprintf(&b, "\t%q: true,\n", n)
	}
	b.WriteString("}\n")

	src, err := format.Source([]byte(b.String()))
	if err != nil {
		log.Fatalf("blacklistgen: format: %v", err)
	}
	if err := os.WriteFile(output, src, 0o644); err != nil {
		log.Fatalf("blacklistgen: write: %v", err)
	}
	log.Printf("blacklistgen: wrote %s (%d entries)", output, len(names))
}
