apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: usmp-system

resources:
  # CRD Definitions
  - ../../config/crd/bases
  # Namespace
  - namespace.yaml
  # Controller
  - controller/service_account.yaml
  - controller/role.yaml
  - controller/role_binding.yaml
  - controller/deployment.yaml
  - controller/service.yaml
  # Frontend
  - frontend/service_account.yaml
  - frontend/cluster_role.yaml
  - frontend/cluster_role_binding.yaml
  - frontend/configmap.yaml
  - frontend/deployment.yaml
  - frontend/service.yaml
  # NETCONF Simulator
  - netconf-simulator/configmap.yaml
  - netconf-simulator/deployment.yaml
  - netconf-simulator/service.yaml

commonLabels:
  app: usmp
  environment: development
