package intent

import (
	"encoding/json"
	"fmt"

	"k8s.io/apimachinery/pkg/apis/meta/v1/unstructured"
	"k8s.io/apimachinery/pkg/runtime/schema"

	"github.com/leezesi/usmp/backend/internal/generated/business"
)

// GVK identifies the BusinessVlanService CR (manifest generated by tools/crdgen
// from usmp-business-vlan.yang — BIC-01/BIC-02).
var GVK = schema.GroupVersionKind{Group: "biz.usmp.io", Version: "v1alpha1", Kind: "BusinessVlanService"}

// IntentPath keys business-vlan intent events in the Stack B queue. It is not a
// device YANG path — intent requests carry the CR key in Request.DeviceID.
const IntentPath = "/business:vlan-service"

// DecodeSpec converts a CR's .spec into the typed ygot intent struct and
// validates it against the YANG schema (range/pattern/mandatory — the same
// rules the CRD OpenAPI enforces apiserver-side; this is the controller-side
// admission-by-watch backstop for direct writes, BIC-03).
func DecodeSpec(u *unstructured.Unstructured) (*business.UsmpBusinessVlan_BusinessVlanService, error) {
	spec, found, err := unstructured.NestedMap(u.Object, "spec")
	if err != nil || !found {
		return nil, fmt.Errorf("decode intent %s: missing spec (%v)", u.GetName(), err)
	}
	// RFC7951 形状：spec 属性名与 YANG 叶子名 1:1（crdgen 保留原名），包一层
	// 顶层容器即可走 ygot Unmarshal（R04：不手写解析）。
	payload, err := json.Marshal(map[string]interface{}{"business-vlan-service": spec})
	if err != nil {
		return nil, fmt.Errorf("decode intent %s: marshal spec: %w", u.GetName(), err)
	}
	root := &business.Device{}
	if err := business.Unmarshal(payload, root); err != nil {
		return nil, fmt.Errorf("decode intent %s: %w", u.GetName(), err)
	}
	if root.BusinessVlanService == nil {
		return nil, fmt.Errorf("decode intent %s: empty business-vlan-service", u.GetName())
	}
	if err := root.Validate(); err != nil {
		return nil, fmt.Errorf("validate intent %s: %w", u.GetName(), err)
	}
	return root.BusinessVlanService, nil
}
