package intent

import (
	"encoding/json"
	"fmt"

	"k8s.io/apimachinery/pkg/apis/meta/v1/unstructured"
	// k8s 的 runtime/schema 与本仓 yang-runtime/schema 重名，前者只用于 GVK，
	// 故别名让位——校验走的是后者。
	k8sschema "k8s.io/apimachinery/pkg/runtime/schema"

	"github.com/leezesi/usmp/backend/internal/generated/native/business"
	"github.com/leezesi/usmp/backend/internal/yangschema"
	"github.com/leezesi/usmp/backend/pkg/yang-runtime/schema"
)

// GVK identifies the BusinessVlanService CR (manifest generated by tools/crdgen
// from usmp-business-vlan.yang — BIC-01/BIC-02).
var GVK = k8sschema.GroupVersionKind{Group: "biz.usmp.io", Version: "v1alpha1", Kind: "BusinessVlanService"}

// IntentPath keys business-vlan intent events in the Stack B queue. It is not a
// device YANG path — intent requests carry the CR key in Request.DeviceID.
const IntentPath = "/business:vlan-service"

// DecodeSpec converts a CR's .spec into the typed ygot intent struct and
// validates it against the YANG schema (range/pattern/mandatory — the same
// rules the CRD OpenAPI enforces apiserver-side; this is the controller-side
// admission-by-watch backstop for direct writes, BIC-03).
func DecodeSpec(u *unstructured.Unstructured) (*business.UsmpBusinessVlan_BusinessVlanService, error) {
	spec, found, err := unstructured.NestedMap(u.Object, "spec")
	if err != nil || !found {
		return nil, fmt.Errorf("decode intent %s: missing spec (%v)", u.GetName(), err)
	}
	// RFC7951 形状：spec 属性名与 YANG 叶子名 1:1（crdgen 保留原名），包一层
	// 顶层容器即可走 ygot Unmarshal（R04：不手写解析）。
	payload, err := json.Marshal(map[string]interface{}{"business-vlan-service": spec})
	if err != nil {
		return nil, fmt.Errorf("decode intent %s: marshal spec: %w", u.GetName(), err)
	}
	root := &business.Device{}
	if err := business.Unmarshal(payload, root); err != nil {
		return nil, fmt.Errorf("decode intent %s: %w", u.GetName(), err)
	}
	if root.BusinessVlanService == nil {
		return nil, fmt.Errorf("decode intent %s: empty business-vlan-service", u.GetName())
	}
	// IR 校验器（retire-ygot-runtime 任务5.2）：替代 ygot 生成的 Validate()，
	// 语义冻结=快照双跑一致（validate_snapshot_test/validate_dual_test）。
	if err := validateIntent(root.BusinessVlanService); err != nil {
		return nil, fmt.Errorf("validate intent %s: %w", u.GetName(), err)
	}
	return root.BusinessVlanService, nil
}

// validateIntent runs the IR-driven constraint validator against the intent
// subtree（pattern/range/length/min-elements，YN-04）。schema 树取不到时快速
// 失败——宁可拒绝写入也不放行未校验意图（R08 的保守侧）。
func validateIntent(v interface{}) error {
	s, err := yangschema.Load()
	if err != nil {
		return fmt.Errorf("schema load: %w", err)
	}
	node, ok := s.Path("/business-vlan-service")
	if !ok {
		return fmt.Errorf("business-vlan-service schema node missing")
	}
	return schema.ValidateObject(node, v)
}
