# ygot 生成配置（make gen-yang 消费；yang_path 相对仓库根）
yang_path=yang-models/network-router/8.20.10/ne40e-x8x16
modules=huawei-vlan huawei-ifm huawei-system huawei-pub-type huawei-extension huawei-bgp huawei-network-instance
generate_fakeroot=true
compress_paths=false
