/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/business/vlan-services": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 列出业务 VLAN 打通意图实例 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 实例清单（含收敛状态） */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["api.Response"] & {
                            data?: components["schemas"]["api.BusinessListData"];
                        };
                    };
                };
                /** @description 未连接集群，业务配置不可用 */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["api.Response"];
                    };
                };
            };
        };
        put?: never;
        /** 创建/更新业务 VLAN 打通意图实例 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description 实例名 + 意图 spec（结构由 usmp-business-vlan YANG 定义） */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["api.BusinessApplyRequest"];
                };
            };
            responses: {
                /** @description 已提交（控制器异步收敛，状态见 status） */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["api.Response"] & {
                            data?: components["schemas"]["api.BusinessVlanServiceItem"];
                        };
                    };
                };
                /** @description spec 违反意图 YANG 约束 */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["api.Response"];
                    };
                };
                /** @description 未连接集群 */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["api.Response"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/business/vlan-services/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 读取单个业务 VLAN 打通意图实例 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description 实例名 */
                    name: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 实例详情 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["api.Response"] & {
                            data?: components["schemas"]["api.BusinessVlanServiceItem"];
                        };
                    };
                };
                /** @description 实例不存在 */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["api.Response"];
                    };
                };
                /** @description 未连接集群 */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["api.Response"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        /** 删除业务 VLAN 打通意图实例（设备配置由控制器清理后放行） */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description 实例名 */
                    name: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 删除已受理 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["api.Response"];
                    };
                };
                /** @description 实例不存在 */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["api.Response"];
                    };
                };
                /** @description 未连接集群 */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["api.Response"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/config/changeset/commit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 变更集批量原子提交（整体生效或整体回退） */
        post: {
            parameters: {
                query?: {
                    /** @description 覆盖业务意图归属硬锁（force=true，审计留痕） */
                    force?: boolean;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: components["requestBodies"]["api.ChangesetReq"];
            responses: {
                /** @description 已提交并触发对账 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["api.Response"] & {
                            data?: components["schemas"]["api.ChangesetCommitData"];
                        };
                    };
                };
                /** @description 变更集解析失败 */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["api.Response"];
                    };
                };
                /** @description 路径被业务意图认领（无 force 拒绝） */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["api.Response"] & {
                            data?: components["schemas"]["api.OwnershipRejection"];
                        };
                    };
                };
                /** @description 设备下发失败（已整体回退） */
                502: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["api.Response"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/config/changeset/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 变更集试运行预览（正向/回滚报文 + diff 树，不下发） */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: components["requestBodies"]["api.ChangesetReq"];
            responses: {
                /** @description 预览结果 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["api.Response"] & {
                            data?: components["schemas"]["api.ChangesetPreviewData"];
                        };
                    };
                };
                /** @description 变更集解析失败 */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["api.Response"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/config/{ip}/{path}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 读取设备指定 YANG 路径的运行配置 */
        get: {
            parameters: {
                query?: {
                    /** @description 绕缓存/快照强制回读设备（BR-04/BR-14） */
                    force_refresh?: boolean;
                    /** @description 状态通道 <get>：含 config=false 数据，短 TTL 快照缓存（BR-14） */
                    include_state?: boolean;
                    /** @description 分页模式（BR-13，仅 YANG list 路径）：每页行数 1..1000，出现即分页，data 变为 {rows,total,limit,offset} */
                    limit?: number;
                    /** @description 分页起始行（缺省 0） */
                    offset?: number;
                    /** @description 过滤条件，可重复：<leaf>==<值> 等值 / <leaf>~=<值> 包含（AND 组合） */
                    filter?: string[];
                    /** @description 排序字段（叶名，支持嵌套路径） */
                    sort?: string;
                    /** @description 排序方向 asc|desc（缺省 asc） */
                    sort_dir?: string;
                };
                header?: never;
                path: {
                    /** @description 设备 IP */
                    ip: string;
                    /** @description YANG 路径 */
                    path: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 运行配置（无分页参数：data 为子树；分页模式：data 为行切片与总数） */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["api.Response"] & {
                            data?: components["schemas"]["api.ConfigGetData"];
                        };
                    };
                };
                /** @description 分页参数非法或目标非 list 节点 */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["api.Response"];
                    };
                };
                /** @description 获取失败 */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["api.Response"];
                    };
                };
                /** @description 设备未连接 */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["api.Response"];
                    };
                };
            };
        };
        put?: never;
        /** 声明式下发配置并触发对账 */
        post: {
            parameters: {
                query?: {
                    /** @description 覆盖业务意图归属硬锁（force=true，审计留痕） */
                    force?: boolean;
                };
                header?: never;
                path: {
                    /** @description 设备 IP */
                    ip: string;
                    /** @description YANG 路径 */
                    path: string;
                };
                cookie?: never;
            };
            /** @description 期望配置（YANG JSON） */
            requestBody: {
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            responses: {
                /** @description 已接受，对账进行中 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["api.Response"] & {
                            data?: components["schemas"]["api.ConfigSetData"];
                        };
                    };
                };
                /** @description 请求或配置解析失败 */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["api.Response"];
                    };
                };
                /** @description 路径被业务意图认领（无 force 拒绝） */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["api.Response"] & {
                            data?: components["schemas"]["api.OwnershipRejection"];
                        };
                    };
                };
                /** @description 存储失败 */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["api.Response"];
                    };
                };
            };
        };
        /** 删除设备指定 YANG 列表路径下的单条目 */
        delete: {
            parameters: {
                query: {
                    /** @description 条目主键（vlan→id，interface→name） */
                    key: string;
                    /** @description 覆盖业务意图归属硬锁（force=true，审计留痕） */
                    force?: boolean;
                };
                header?: never;
                path: {
                    /** @description 设备 IP */
                    ip: string;
                    /** @description YANG 列表路径 */
                    path: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 删除成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["api.Response"] & {
                            data?: components["schemas"]["api.ConfigDeleteData"];
                        };
                    };
                };
                /** @description 非法 key / 未知路径 / 模型门禁拒绝 */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["api.Response"];
                    };
                };
                /** @description 条目被业务意图认领（无 force 拒绝） */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["api.Response"] & {
                            data?: components["schemas"]["api.OwnershipRejection"];
                        };
                    };
                };
                /** @description 设备删除失败（含 data-missing） */
                502: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["api.Response"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/devices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 列出所有设备及在线状态 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 设备列表 + 连接池统计 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["api.Response"] & {
                            data?: components["schemas"]["api.DeviceListData"];
                        };
                    };
                };
            };
        };
        put?: never;
        /** 添加设备并即时建连 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description 设备连接信息 */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["api.AddDeviceRequest"];
                };
            };
            responses: {
                /** @description 添加成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["api.Response"];
                    };
                };
                /** @description 请求非法 */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["api.Response"];
                    };
                };
                /** @description 连接设备失败 */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["api.Response"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/devices/{ip}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** 移除设备并释放连接 */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description 设备 IP */
                    ip: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 移除成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["api.Response"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/devices/{ip}/capabilities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 查询设备 hello capabilities 原文 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description 设备 IP */
                    ip: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description capabilities 原文；离线为空列表+negotiated:false */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["api.Response"] & {
                            data?: components["schemas"]["api.DeviceCapabilitiesData"];
                        };
                    };
                };
                /** @description 设备未注册 */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["api.Response"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/devices/{ip}/reconcile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 读取单设备对账结局（desired↔actual，含各 YANG 路径明细） */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description 设备 IP */
                    ip: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 设备对账结局；从未对账返回 outcome=unknown */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["api.Response"] & {
                            data?: components["schemas"]["api.DeviceReconcileData"];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/devices/{ip}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 查询设备运行/连接状态 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description 设备 IP */
                    ip: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 运行与连接状态 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["api.Response"] & {
                            data?: components["schemas"]["api.DeviceConnStatus"];
                        };
                    };
                };
                /** @description 设备不存在 */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["api.Response"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 操作日志（配置下发审计 + 当前对账结局） */
        get: {
            parameters: {
                query?: {
                    /** @description 按设备 IP 筛选 */
                    device?: string;
                    /** @description 按当前对账结局筛选(converged/drifted/error/reconciling/unknown) */
                    status?: string;
                    /** @description 每页条数(默认 50，上限 500) */
                    limit?: number;
                    /** @description 偏移(默认 0) */
                    offset?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 操作日志 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["api.Response"] & {
                            data?: components["schemas"]["api.AuditListData"];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ownership/{device}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 查询设备原生配置的业务意图归属（软归属，BIO-07） */
        get: {
            parameters: {
                query?: {
                    /** @description 原生 YANG 路径（前缀匹配；缺省返回设备全量认领） */
                    path?: string;
                };
                header?: never;
                path: {
                    /** @description 设备 IP */
                    device: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 归属信息（未认领时 intents/claims 为空） */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["api.Response"] & {
                            data?: components["schemas"]["api.OwnershipData"];
                        };
                    };
                };
                /** @description 缺少设备参数 */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["api.Response"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reconcile/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 全网对账结局聚合（收敛台账 / 概览大盘用） */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 全网对账结局聚合；summary 按结局计数，仅含已对账设备（unknown 需与设备列表相减派生） */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["api.Response"] & {
                            data?: components["schemas"]["api.FleetReconcileData"];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rpc/{ip}/{module}/{rpc}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 执行模块 rpc（运维操作） */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description 设备 IP */
                    ip: string;
                    /** @description 模块（根容器名） */
                    module: string;
                    /** @description rpc 名 */
                    rpc: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 执行结果（ok/reply） */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["api.Response"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/yang/left-tree": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取 SND 左树（原生配置导航，含可用性标注） */
        get: {
            parameters: {
                query?: {
                    /** @description 按设备 hello 能力叠加 supported 标注 */
                    device?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 左树 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["api.Response"] & {
                            data?: components["schemas"]["api.LeftTreeNodeDTO"][];
                        };
                    };
                };
                /** @description device 未注册（信封） */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["api.Response"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/yang/modules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 列出所有支持的 YANG 模块 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 模块列表 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["api.Response"] & {
                            data?: components["schemas"]["api.YangModuleInfo"][];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/yang/schema/{module}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取指定 YANG 模块的动态表单 schema */
        get: {
            parameters: {
                query?: {
                    /** @description nested 返回嵌套树 schema（保留 list-in-list 结构） */
                    form?: string;
                };
                header?: never;
                path: {
                    /** @description 模块名 */
                    module: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 动态表单 schema */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["api.Response"] & {
                            data?: components["schemas"]["api.YangSchema"];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        "api.AddDeviceRequest": {
            ip: string;
            password: string;
            port?: number;
            /** @description Role 可选网络角色标签：≤32 字符且仅 [A-Za-z0-9_-]，非法 400（BR-14） */
            role?: string;
            username: string;
            /** @description Vendor 可选厂商标识：缺省 huawei；无已注册驱动的厂商将被拒绝（400） */
            vendor?: string;
        };
        "api.AuditListData": {
            logs?: components["schemas"]["api.LogEntry"][];
            total?: number;
        };
        "api.BusinessApplyRequest": {
            name: string;
            spec: {
                [key: string]: unknown;
            };
        };
        "api.BusinessListData": {
            items?: components["schemas"]["api.BusinessVlanServiceItem"][];
        };
        "api.BusinessVlanServiceItem": {
            name?: string;
            spec?: {
                [key: string]: unknown;
            };
            status?: {
                [key: string]: unknown;
            };
        };
        "api.CaseDef": {
            fields?: components["schemas"]["api.FieldDef"][];
            label?: string;
            name?: string;
        };
        "api.ChangesetCommitData": {
            device?: string;
            entries?: number;
            /** @description NonTransactional 标记设备缺 :confirmed-commit 降级普通 commit（DP-08）。 */
            non_transactional?: boolean;
            reconciliation?: components["schemas"]["api.ReconcileInfo"];
            /** @description COMMITTED */
            status?: string;
        };
        "api.ChangesetEntryReq": {
            /** @description update：字段级清除的叶名（CS-05） */
            cleared?: string[];
            /** @description delete：list 主键值 */
            key?: string;
            /** @description create | update | delete */
            op?: string;
            /** @description 请求路径（锚点或其子路径） */
            path?: string;
            /** @description create/update：以 path 为根的 RFC7951 子树 */
            payload?: {
                [key: string]: unknown;
            };
        };
        "api.ChangesetPreviewData": {
            device?: string;
            entries?: components["schemas"]["api.ChangesetPreviewEntry"][];
            summary?: components["schemas"]["api.ChangesetSummary"];
        };
        "api.ChangesetPreviewEntry": {
            /** @description desired | cache | device | none */
            baseline_source?: string;
            diff?: components["schemas"]["api.DiffChangeDTO"][];
            /**
             * @description ForwardXML/RollbackXML 为 edit-config 片段；无 XML 通道时为空且
             *     Unsupported=true（CS-03 如实降级，绝不伪造报文）。
             */
            forward_xml?: string;
            op?: string;
            path?: string;
            rollback_xml?: string;
            unsupported?: boolean;
            unsupported_reason?: string;
        };
        "api.ChangesetReq": {
            device?: string;
            entries?: components["schemas"]["api.ChangesetEntryReq"][];
        };
        "api.ChangesetSummary": {
            adds?: number;
            deletes?: number;
            modifies?: number;
            total?: number;
        };
        "api.ConfigDeleteData": {
            key?: string;
            /** @description OwnershipWarning 软归属提示（BR-11）：条目被业务意图认领时附带，不拦截。 */
            ownershipWarning?: components["schemas"]["api.OwnershipWarning"];
            path?: string;
            reconciliation?: components["schemas"]["api.ReconcileInfo"];
            status?: string;
        };
        "api.ConfigGetData": {
            cache_age_seconds?: number;
            cached?: boolean;
            data?: unknown;
            /** @description "device" | "cache" */
            source?: string;
            ttl_seconds?: number;
        };
        "api.ConfigSetData": {
            /** @description OwnershipWarning 软归属提示（BR-11）：路径被业务意图认领时附带，不拦截。 */
            ownershipWarning?: components["schemas"]["api.OwnershipWarning"];
            path?: string;
            reconciliation?: components["schemas"]["api.ReconcileInfo"];
            status?: string;
        };
        "api.DeviceCapabilitiesData": {
            capabilities?: string[];
            negotiated?: boolean;
        };
        "api.DeviceConnStatus": {
            connected?: boolean;
            running?: boolean;
        };
        "api.DeviceListData": {
            devices?: components["schemas"]["api.DeviceStatus"][];
            stats?: components["schemas"]["api.PoolStatsDTO"];
        };
        "api.DeviceReconcileData": {
            device_id?: string;
            outcome?: string;
            statuses?: components["schemas"]["github_com_leezesi_usmp_backend_pkg_yang-runtime_status.Status"][];
        };
        "api.DeviceRollup": {
            device_id?: string;
            last_run?: string;
            outcome?: string;
        };
        "api.DeviceStatus": {
            ip?: string;
            online?: boolean;
            password?: string;
            port?: number;
            /** @description Role 网络角色标签（DCGW/EOR/TOR/BORDER 等；展示/策略用途，BR-14） */
            role?: string;
            username?: string;
            /** @description Vendor 厂商标识（SND 驱动选择，缺省 huawei） */
            vendor?: string;
        };
        "api.DiffChangeDTO": {
            new?: unknown;
            old?: unknown;
            path?: string;
            /** @description ADD | DELETE | MODIFY */
            type?: string;
        };
        "api.FieldDef": {
            /**
             * @description Cases 承载 YANG `choice` 的互斥分支：type=choice 时非空，每个 case 携带自身子字段。
             *     前端据此渲染 Tabs/RadioGroup（BR-06）。case 子字段 path 为扁平数据路径。
             */
            cases?: components["schemas"]["api.CaseDef"][];
            default?: unknown;
            /**
             * @description DynamicDefault 标记厂商 `dynamic-default` 扩展（BR-10）：值由系统动态缺省，
             *     空值=「设备自行决定」而非缺配置——前端展示自动分配占位、不强制必填。
             */
            dynamicDefault?: boolean;
            /**
             * @description Fields 承载嵌套子字段：type=group（单个嵌套对象）/ type=list（可重复列表）时非空。
             *     由 ?form=nested 的嵌套 schema 生成，用于 member-ports 等 list-in-list 结构（R05）。
             */
            fields?: components["schemas"]["api.FieldDef"][];
            group?: string;
            /**
             * @description IsKey 标记 list 的 key 叶：通用控制台据此派生 keyField/首列，免去 per-module
             *     路由 props（BR-07）。
             */
            isKey?: boolean;
            label?: string;
            /**
             * @description LeafRef 携带 leafref 目标 XPath（RPC-02）：非空时前端可据此渲染为目标值下拉
             *     （如 rpc 输入 if-name→接口名）。配置叶目前不填（omitempty），首用于 rpc 输入。
             */
            leafRef?: string;
            maxLength?: number;
            maximum?: number;
            /** @description MinLength/MaxLength 承载字符串 `length` 约束（D9）：前端合成「合法长度」占位（FE-22）。 */
            minLength?: number;
            minimum?: number;
            /** @description Must 携带 YANG `must` 约束（XPath 表达式 + 提示），驱动前端跨字段校验（R05）。 */
            must?: components["schemas"]["api.MustRule"][];
            /**
             * @description OperationExclude 承载厂商 `operation-exclude` 扩展（小写归一）：叶级表示
             *     create-only 标识字段（编辑态禁用），list/group 级表示整节点排除对应操作（BR-07）。
             */
            operationExclude?: string[];
            options?: components["schemas"]["api.Option"][];
            path?: string;
            pattern?: string;
            placeholder?: string;
            /**
             * @description Presence 标记 YANG presence 容器（type=group 时有意义）：节点存在与否即开关，
             *     前端渲染为 switch、关闭时键不入 payload（BR-08）。
             */
            presence?: boolean;
            readonly?: boolean;
            required?: boolean;
            /**
             * @description SupportFilter 标记厂商 `support-filter` 扩展：该叶可作查询条件，驱动前端
             *     高级搜索控件（BR-07）。
             */
            supportFilter?: boolean;
            type?: string;
            /** @description Units 携带 YANG `units`（BR-09）：输入控件展示单位后缀（如 bit/s）。 */
            units?: string;
            /** @description When 携带 YANG `when` XPath 表达式，驱动前端数据驱动的条件显隐（R05）。空表示无条件。 */
            when?: string;
        };
        "api.FleetReconcileData": {
            devices?: components["schemas"]["api.DeviceRollup"][];
            summary?: {
                [key: string]: number;
            };
        };
        "api.LeftTreeNodeDTO": {
            /** @description Available 标记叶子模块是否已接入（根容器已加载）；仅叶子携带。 */
            available?: boolean;
            children?: components["schemas"]["api.LeftTreeNodeDTO"][];
            en?: string;
            highRisk?: boolean;
            /**
             * @description Kind/Name/HighRisk 仅模块级子节点携带（LT-02 children）：kind=container 路由
             *     /module/<name>，kind=rpc 路由 /module/<父叶module>/rpc/<name>；highRisk 仅
             *     高危 rpc 为 true 时出现。分组与模块叶自身省略（契约向后兼容）。
             */
            kind?: string;
            /** @description Module 是首个已加载根容器名（前端路由 /module/<module>）；不可用叶省略。 */
            module?: string;
            name?: string;
            /** @description SourceModule 是叶子的 SND 源模块名（如 huawei-vlan）；分组为空。 */
            sourceModule?: string;
            /** @description Supported 标记该设备 hello 能力是否覆盖此模块；仅 ?device= 且协商可得时携带。 */
            supported?: boolean;
            zh?: string;
        };
        "api.LogEntry": {
            actor?: string;
            device_ip?: string;
            /** @description 当前差异数（live-join） */
            diff_count?: number;
            /** @description Forced/ForcedOwners：force 覆盖归属硬锁留痕（OA-01 二期，零值省略）。 */
            forced?: boolean;
            forcedOwners?: string[];
            id?: string;
            /** @description 当前对账结局（live-join；无记录为 unknown） */
            outcome?: string;
            path?: string;
            summary?: string;
            timestamp?: string;
            triggered?: boolean;
        };
        "api.MustRule": {
            expr?: string;
            message?: string;
        };
        "api.Option": {
            label?: string;
            value?: unknown;
        };
        "api.OwnershipClaim": {
            /** @description Intent 认领方（意图 CR 的 namespace/name）。 */
            intent?: string;
            module?: string;
            path?: string;
        };
        "api.OwnershipData": {
            /** @description Claims 设备全量认领（无 path 查询模式）。 */
            claims?: components["schemas"]["api.OwnershipClaim"][];
            device?: string;
            /** @description Intents 命中 path 的认领意图（path 查询模式）。 */
            intents?: string[];
            /** @description Path 为空时返回该设备全部认领。 */
            path?: string;
        };
        "api.OwnershipRejection": {
            /** @description Intents 认领该路径的意图 CR（namespace/name）。 */
            intents?: string[];
        };
        "api.OwnershipWarning": {
            /** @description Intents 认领该路径的意图 CR（namespace/name）。 */
            intents?: string[];
            message?: string;
        };
        "api.PoolStatsDTO": {
            active_connections?: number;
            errors?: number;
            total_connections?: number;
        };
        "api.RPCSchema": {
            highRisk?: boolean;
            input?: components["schemas"]["api.FieldDef"][];
            label?: string;
            name?: string;
        };
        "api.ReconcileInfo": {
            message?: string;
            triggered?: boolean;
        };
        "api.Response": {
            code?: number;
            data?: unknown;
            message?: string;
            success?: boolean;
        };
        "api.YangModuleInfo": {
            /** @description Blacklisted 标记该模块命中 SND blacklist（CN-03 注解语义，不据此裁剪）。 */
            blacklisted?: boolean;
            /**
             * @description Category 是模块所属任务域（源 YANG 模块级 task-name 扩展，构建期提取，BR-01）：
             *     驱动前端左导航分组；无映射省略（omitempty，R08）。
             */
            category?: string;
            description?: string;
            name?: string;
            path?: string;
            title?: string;
            type?: string;
            vendor?: string;
        };
        "api.YangSchema": {
            fields?: components["schemas"]["api.FieldDef"][];
            listCols?: components["schemas"]["api.FieldDef"][];
            module?: string;
            /** @description RPCs 是该模块的 rpc（RPC-02）：与配置节点平级，input 复用 FieldDef 渲染。 */
            rpcs?: components["schemas"]["api.RPCSchema"][];
            title?: string;
            /**
             * @description Unsupported 该设备已学习的不支持子路径（相对模块根首段名，CN-05）：仅
             *     ?device= 形态携带，空集省略；前端据此预标记占位 Tab（FE-24）。
             */
            unsupported?: string[];
            vendor?: string;
        };
        "github_com_leezesi_usmp_backend_pkg_yang-runtime_status.Status": {
            device_id?: string;
            diff_count?: number;
            last_error?: string;
            last_run?: string;
            outcome?: components["schemas"]["status.Outcome"];
            path?: string;
        };
        /** @enum {string} */
        "status.Outcome": "unknown" | "converged" | "drifted" | "reconciling" | "error";
    };
    responses: never;
    parameters: never;
    requestBodies: {
        /** @description 单设备变更集 */
        "api.ChangesetReq": {
            content: {
                "application/json": components["schemas"]["api.ChangesetReq"];
            };
        };
    };
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
