/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/business/vlan-services": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 列出业务 VLAN 打通意图实例 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 实例清单（含收敛状态） */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["api.Response"] & {
                            data?: components["schemas"]["api.BusinessListData"];
                        };
                    };
                };
                /** @description 未连接集群，业务配置不可用 */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["api.Response"];
                    };
                };
            };
        };
        put?: never;
        /** 创建/更新业务 VLAN 打通意图实例 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description 实例名 + 意图 spec（结构由 usmp-business-vlan YANG 定义） */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["api.BusinessApplyRequest"];
                };
            };
            responses: {
                /** @description 已提交（控制器异步收敛，状态见 status） */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["api.Response"] & {
                            data?: components["schemas"]["api.BusinessVlanServiceItem"];
                        };
                    };
                };
                /** @description spec 违反意图 YANG 约束 */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["api.Response"];
                    };
                };
                /** @description 未连接集群 */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["api.Response"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/business/vlan-services/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 读取单个业务 VLAN 打通意图实例 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description 实例名 */
                    name: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 实例详情 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["api.Response"] & {
                            data?: components["schemas"]["api.BusinessVlanServiceItem"];
                        };
                    };
                };
                /** @description 实例不存在 */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["api.Response"];
                    };
                };
                /** @description 未连接集群 */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["api.Response"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        /** 删除业务 VLAN 打通意图实例（设备配置由控制器清理后放行） */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description 实例名 */
                    name: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 删除已受理 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["api.Response"];
                    };
                };
                /** @description 实例不存在 */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["api.Response"];
                    };
                };
                /** @description 未连接集群 */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["api.Response"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/config/{ip}/{path}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 读取设备指定 YANG 路径的运行配置 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description 设备 IP */
                    ip: string;
                    /** @description YANG 路径 */
                    path: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 运行配置 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["api.Response"] & {
                            data?: components["schemas"]["api.ConfigGetData"];
                        };
                    };
                };
                /** @description 获取失败 */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["api.Response"];
                    };
                };
                /** @description 设备未连接 */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["api.Response"];
                    };
                };
            };
        };
        put?: never;
        /** 声明式下发配置并触发对账 */
        post: {
            parameters: {
                query?: {
                    /** @description 覆盖业务意图归属硬锁（force=true，审计留痕） */
                    force?: boolean;
                };
                header?: never;
                path: {
                    /** @description 设备 IP */
                    ip: string;
                    /** @description YANG 路径 */
                    path: string;
                };
                cookie?: never;
            };
            /** @description 期望配置（YANG JSON） */
            requestBody: {
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            responses: {
                /** @description 已接受，对账进行中 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["api.Response"] & {
                            data?: components["schemas"]["api.ConfigSetData"];
                        };
                    };
                };
                /** @description 请求或配置解析失败 */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["api.Response"];
                    };
                };
                /** @description 路径被业务意图认领（无 force 拒绝） */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["api.Response"] & {
                            data?: components["schemas"]["api.OwnershipRejection"];
                        };
                    };
                };
                /** @description 存储失败 */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["api.Response"];
                    };
                };
            };
        };
        /** 删除设备指定 YANG 列表路径下的单条目 */
        delete: {
            parameters: {
                query: {
                    /** @description 条目主键（vlan→id，interface→name） */
                    key: string;
                    /** @description 覆盖业务意图归属硬锁（force=true，审计留痕） */
                    force?: boolean;
                };
                header?: never;
                path: {
                    /** @description 设备 IP */
                    ip: string;
                    /** @description YANG 列表路径 */
                    path: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 删除成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["api.Response"] & {
                            data?: components["schemas"]["api.ConfigDeleteData"];
                        };
                    };
                };
                /** @description 非法 key / 未知路径 / 模型门禁拒绝 */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["api.Response"];
                    };
                };
                /** @description 条目被业务意图认领（无 force 拒绝） */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["api.Response"] & {
                            data?: components["schemas"]["api.OwnershipRejection"];
                        };
                    };
                };
                /** @description 设备删除失败（含 data-missing） */
                502: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["api.Response"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/devices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 列出所有设备及在线状态 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 设备列表 + 连接池统计 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["api.Response"] & {
                            data?: components["schemas"]["api.DeviceListData"];
                        };
                    };
                };
            };
        };
        put?: never;
        /** 添加设备并即时建连 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description 设备连接信息 */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["api.AddDeviceRequest"];
                };
            };
            responses: {
                /** @description 添加成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["api.Response"];
                    };
                };
                /** @description 请求非法 */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["api.Response"];
                    };
                };
                /** @description 连接设备失败 */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["api.Response"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/devices/{ip}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** 移除设备并释放连接 */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description 设备 IP */
                    ip: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 移除成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["api.Response"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/devices/{ip}/reconcile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 读取单设备对账结局（desired↔actual，含各 YANG 路径明细） */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description 设备 IP */
                    ip: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 设备对账结局；从未对账返回 outcome=unknown */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["api.Response"] & {
                            data?: components["schemas"]["api.DeviceReconcileData"];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/devices/{ip}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 查询设备运行/连接状态 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description 设备 IP */
                    ip: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 运行与连接状态 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["api.Response"] & {
                            data?: components["schemas"]["api.DeviceConnStatus"];
                        };
                    };
                };
                /** @description 设备不存在 */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["api.Response"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 操作日志（配置下发审计 + 当前对账结局） */
        get: {
            parameters: {
                query?: {
                    /** @description 按设备 IP 筛选 */
                    device?: string;
                    /** @description 按当前对账结局筛选(converged/drifted/error/reconciling/unknown) */
                    status?: string;
                    /** @description 每页条数(默认 50，上限 500) */
                    limit?: number;
                    /** @description 偏移(默认 0) */
                    offset?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 操作日志 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["api.Response"] & {
                            data?: components["schemas"]["api.AuditListData"];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ownership/{device}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 查询设备原生配置的业务意图归属（软归属，BIO-07） */
        get: {
            parameters: {
                query?: {
                    /** @description 原生 YANG 路径（前缀匹配；缺省返回设备全量认领） */
                    path?: string;
                };
                header?: never;
                path: {
                    /** @description 设备 IP */
                    device: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 归属信息（未认领时 intents/claims 为空） */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["api.Response"] & {
                            data?: components["schemas"]["api.OwnershipData"];
                        };
                    };
                };
                /** @description 缺少设备参数 */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["api.Response"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reconcile/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 车队级对账结局聚合（收敛台账 / 概览大盘用） */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 车队对账聚合；summary 按结局计数，仅含已对账设备（unknown 需与设备列表相减派生） */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["api.Response"] & {
                            data?: components["schemas"]["api.FleetReconcileData"];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/yang/modules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 列出所有支持的 YANG 模块 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 模块列表 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["api.Response"] & {
                            data?: components["schemas"]["api.YangModuleInfo"][];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/yang/schema/{module}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取指定 YANG 模块的动态表单 schema */
        get: {
            parameters: {
                query?: {
                    /** @description nested 返回嵌套树 schema（保留 list-in-list 结构） */
                    form?: string;
                };
                header?: never;
                path: {
                    /** @description 模块名 */
                    module: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 动态表单 schema */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["api.Response"] & {
                            data?: components["schemas"]["api.YangSchema"];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        "api.AddDeviceRequest": {
            ip: string;
            password: string;
            port?: number;
            /** @description Role 可选网络角色标签：≤32 字符且仅 [A-Za-z0-9_-]，非法 400（BR-14） */
            role?: string;
            username: string;
            /** @description Vendor 可选厂商标识：缺省 huawei；无已注册驱动的厂商将被拒绝（400） */
            vendor?: string;
        };
        "api.AuditListData": {
            logs?: components["schemas"]["api.LogEntry"][];
            total?: number;
        };
        "api.BusinessApplyRequest": {
            name: string;
            spec: {
                [key: string]: unknown;
            };
        };
        "api.BusinessListData": {
            items?: components["schemas"]["api.BusinessVlanServiceItem"][];
        };
        "api.BusinessVlanServiceItem": {
            name?: string;
            spec?: {
                [key: string]: unknown;
            };
            status?: {
                [key: string]: unknown;
            };
        };
        "api.CaseDef": {
            fields?: components["schemas"]["api.FieldDef"][];
            label?: string;
            name?: string;
        };
        "api.ConfigDeleteData": {
            key?: string;
            /** @description OwnershipWarning 软归属提示（BR-11）：条目被业务意图认领时附带，不拦截。 */
            ownershipWarning?: components["schemas"]["api.OwnershipWarning"];
            path?: string;
            reconciliation?: components["schemas"]["api.ReconcileInfo"];
            status?: string;
        };
        "api.ConfigGetData": {
            cache_age_seconds?: number;
            cached?: boolean;
            data?: unknown;
            /** @description "device" | "cache" */
            source?: string;
            ttl_seconds?: number;
        };
        "api.ConfigSetData": {
            /** @description OwnershipWarning 软归属提示（BR-11）：路径被业务意图认领时附带，不拦截。 */
            ownershipWarning?: components["schemas"]["api.OwnershipWarning"];
            path?: string;
            reconciliation?: components["schemas"]["api.ReconcileInfo"];
            status?: string;
        };
        "api.DeviceConnStatus": {
            connected?: boolean;
            running?: boolean;
        };
        "api.DeviceListData": {
            devices?: components["schemas"]["api.DeviceStatus"][];
            stats?: components["schemas"]["api.PoolStatsDTO"];
        };
        "api.DeviceReconcileData": {
            device_id?: string;
            outcome?: string;
            statuses?: components["schemas"]["github_com_leezesi_usmp_backend_pkg_yang-runtime_status.Status"][];
        };
        "api.DeviceRollup": {
            device_id?: string;
            last_run?: string;
            outcome?: string;
        };
        "api.DeviceStatus": {
            ip?: string;
            online?: boolean;
            password?: string;
            port?: number;
            /** @description Role 网络角色标签（DCGW/EOR/TOR/BORDER 等；展示/策略用途，BR-14） */
            role?: string;
            username?: string;
            /** @description Vendor 厂商标识（SND 驱动选择，缺省 huawei） */
            vendor?: string;
        };
        "api.FieldDef": {
            /**
             * @description Cases 承载 YANG `choice` 的互斥分支：type=choice 时非空，每个 case 携带自身子字段。
             *     前端据此渲染 Tabs/RadioGroup（BR-06）。case 子字段 path 为扁平数据路径。
             */
            cases?: components["schemas"]["api.CaseDef"][];
            default?: unknown;
            /**
             * @description DynamicDefault 标记厂商 `dynamic-default` 扩展（BR-10）：值由系统动态缺省，
             *     空值=「设备自行决定」而非缺配置——前端展示自动分配占位、不强制必填。
             */
            dynamicDefault?: boolean;
            /**
             * @description Fields 承载嵌套子字段：type=group（单个嵌套对象）/ type=list（可重复列表）时非空。
             *     由 ?form=nested 的嵌套 schema 生成，用于 member-ports 等 list-in-list 结构（R05）。
             */
            fields?: components["schemas"]["api.FieldDef"][];
            group?: string;
            /**
             * @description IsKey 标记 list 的 key 叶：通用控制台据此派生 keyField/首列，免去 per-module
             *     路由 props（BR-07）。
             */
            isKey?: boolean;
            label?: string;
            maximum?: number;
            minimum?: number;
            /** @description Must 携带 YANG `must` 约束（XPath 表达式 + 提示），驱动前端跨字段校验（R05）。 */
            must?: components["schemas"]["api.MustRule"][];
            /**
             * @description OperationExclude 承载厂商 `operation-exclude` 扩展（小写归一）：叶级表示
             *     create-only 标识字段（编辑态禁用），list/group 级表示整节点排除对应操作（BR-07）。
             */
            operationExclude?: string[];
            options?: components["schemas"]["api.Option"][];
            path?: string;
            pattern?: string;
            placeholder?: string;
            /**
             * @description Presence 标记 YANG presence 容器（type=group 时有意义）：节点存在与否即开关，
             *     前端渲染为 switch、关闭时键不入 payload（BR-08）。
             */
            presence?: boolean;
            readonly?: boolean;
            required?: boolean;
            /**
             * @description SupportFilter 标记厂商 `support-filter` 扩展：该叶可作查询条件，驱动前端
             *     高级搜索控件（BR-07）。
             */
            supportFilter?: boolean;
            type?: string;
            /** @description Units 携带 YANG `units`（BR-09）：输入控件展示单位后缀（如 bit/s）。 */
            units?: string;
            /** @description When 携带 YANG `when` XPath 表达式，驱动前端数据驱动的条件显隐（R05）。空表示无条件。 */
            when?: string;
        };
        "api.FleetReconcileData": {
            devices?: components["schemas"]["api.DeviceRollup"][];
            summary?: {
                [key: string]: number;
            };
        };
        "api.LogEntry": {
            actor?: string;
            device_ip?: string;
            /** @description 当前差异数（live-join） */
            diff_count?: number;
            /** @description Forced/ForcedOwners：force 覆盖归属硬锁留痕（OA-01 二期，零值省略）。 */
            forced?: boolean;
            forcedOwners?: string[];
            id?: string;
            /** @description 当前对账结局（live-join；无记录为 unknown） */
            outcome?: string;
            path?: string;
            summary?: string;
            timestamp?: string;
            triggered?: boolean;
        };
        "api.MustRule": {
            expr?: string;
            message?: string;
        };
        "api.Option": {
            label?: string;
            value?: unknown;
        };
        "api.OwnershipClaim": {
            /** @description Intent 认领方（意图 CR 的 namespace/name）。 */
            intent?: string;
            module?: string;
            path?: string;
        };
        "api.OwnershipData": {
            /** @description Claims 设备全量认领（无 path 查询模式）。 */
            claims?: components["schemas"]["api.OwnershipClaim"][];
            device?: string;
            /** @description Intents 命中 path 的认领意图（path 查询模式）。 */
            intents?: string[];
            /** @description Path 为空时返回该设备全部认领。 */
            path?: string;
        };
        "api.OwnershipRejection": {
            /** @description Intents 认领该路径的意图 CR（namespace/name）。 */
            intents?: string[];
        };
        "api.OwnershipWarning": {
            /** @description Intents 认领该路径的意图 CR（namespace/name）。 */
            intents?: string[];
            message?: string;
        };
        "api.PoolStatsDTO": {
            active_connections?: number;
            errors?: number;
            total_connections?: number;
        };
        "api.ReconcileInfo": {
            message?: string;
            triggered?: boolean;
        };
        "api.Response": {
            code?: number;
            data?: unknown;
            message?: string;
            success?: boolean;
        };
        "api.YangModuleInfo": {
            /** @description Blacklisted 标记该模块命中 SND blacklist（CN-03 注解语义，不据此裁剪）。 */
            blacklisted?: boolean;
            /**
             * @description Category 是模块所属任务域（源 YANG 模块级 task-name 扩展，构建期提取，BR-01）：
             *     驱动前端左导航分组；无映射省略（omitempty，R08）。
             */
            category?: string;
            description?: string;
            name?: string;
            path?: string;
            title?: string;
            type?: string;
            vendor?: string;
        };
        "api.YangSchema": {
            fields?: components["schemas"]["api.FieldDef"][];
            listCols?: components["schemas"]["api.FieldDef"][];
            module?: string;
            title?: string;
            vendor?: string;
        };
        "github_com_leezesi_usmp_backend_pkg_yang-runtime_status.Status": {
            device_id?: string;
            diff_count?: number;
            last_error?: string;
            last_run?: string;
            outcome?: components["schemas"]["status.Outcome"];
            path?: string;
        };
        /** @enum {string} */
        "status.Outcome": "unknown" | "converged" | "drifted" | "reconciling" | "error";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
