package v1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out.
func (in *NativeDeviceConfig) DeepCopyInto(out *NativeDeviceConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver.
func (in *NativeDeviceConfig) DeepCopy() *NativeDeviceConfig {
	if in == nil {
		return nil
	}
	out := new(NativeDeviceConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver.
func (in *NativeDeviceConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver.
func (in *NativeDeviceConfigSpec) DeepCopyInto(out *NativeDeviceConfigSpec) {
	*out = *in
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver.
func (in *NativeDeviceConfigStatus) DeepCopyInto(out *NativeDeviceConfigStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		copy(*out, *in)
	}
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver.
func (in *NativeDeviceConfigList) DeepCopyInto(out *NativeDeviceConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NativeDeviceConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver.
func (in *NativeDeviceConfigList) DeepCopy() *NativeDeviceConfigList {
	if in == nil {
		return nil
	}
	out := new(NativeDeviceConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver.
func (in *NativeDeviceConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}
