// Command crd2yang generates a YANG module from a northbound-owned Kubernetes
// CRD manifest (C2Y-01..03): the CRD is the schema authority for northbound
// contracts, the YANG module is derived at build time and committed
// (regen-and-diff gate, R04 methodology). Mirror of tools/crdgen (YANG→CRD):
// the two type-mapping tables are mutually inverse, closed by the round-trip
// test (C2Y-04). The authority split (D2) is strict — a model runs exactly one
// direction, never both.
//
// Conventions:
//   - only the unique storage version's .spec subtree is converted; .status is
//     dropped entirely (fixed USMP-side contract, BIC-04);
//   - .spec is wrapped into a single top-level container so the output closes
//     crdgen's single-container convention;
//   - module-level metadata comes from usmp.io/* annotations (C2Y-02); the
//     revision annotation is mandatory — no implicit dates;
//   - OpenAPI constructs outside the mappable set fail fast with the field's
//     JSON path — no silent downgrade (C2Y-03).
package main

import (
	"fmt"
	"regexp"
	"strings"

	apiextv1 "k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1"
	sigsyaml "sigs.k8s.io/yaml"
)

// meta is the module-level metadata resolved from CRD annotations (C2Y-02).
type meta struct {
	crdName   string
	module    string
	namespace string
	prefix    string
	container string
	taskName  string
	revision  string
}

var (
	revisionRe   = regexp.MustCompile(`^\d{4}-\d{2}-\d{2}$`)
	identifierRe = regexp.MustCompile(`^[A-Za-z_][A-Za-z0-9._-]*$`)
)

// Generate parses the CRD manifest and renders the YANG module text.
func Generate(manifest []byte) ([]byte, error) {
	var crd apiextv1.CustomResourceDefinition
	if err := sigsyaml.UnmarshalStrict(manifest, &crd); err != nil {
		return nil, fmt.Errorf("parse manifest: %w", err)
	}
	if crd.Kind != "CustomResourceDefinition" {
		return nil, fmt.Errorf("input kind %q is not a CustomResourceDefinition", crd.Kind)
	}

	version, err := storageVersion(&crd)
	if err != nil {
		return nil, err
	}
	if version.Schema == nil || version.Schema.OpenAPIV3Schema == nil {
		return nil, fmt.Errorf("version %s: missing openAPIV3Schema", version.Name)
	}
	specSchema, ok := version.Schema.OpenAPIV3Schema.Properties["spec"]
	if !ok {
		return nil, fmt.Errorf("openAPIV3Schema has no spec property — northbound contracts carry desired state in .spec")
	}

	m, err := resolveMeta(&crd)
	if err != nil {
		return nil, err
	}

	w := &writer{}
	w.line("// Code generated by crd2yang from CRD %s; DO NOT EDIT.", m.crdName)
	w.line("// 北向 CRD 反向派生（C2Y-01）：CRD 是 schema authority，重生成用 make gen-crd2yang。")
	w.line("module %s {", m.module)
	w.in()
	w.line("namespace %s;", quote(m.namespace))
	w.line("prefix %s;", m.prefix)
	w.blank()
	w.line("organization \"USMP\";")
	w.line("description")
	w.line("  %s;", quote(fmt.Sprintf("业务网络配置模型——由北向 CRD 反向派生（crd2yang，C2Y-01）。generated-from: %s", m.crdName)))
	w.blank()
	w.line("revision %s {", m.revision)
	w.in()
	w.line("description %s;", quote(fmt.Sprintf("Generated from CRD %s.", m.crdName)))
	w.out()
	w.line("}")
	w.blank()
	w.line("extension task-name {")
	w.in()
	w.line("argument name;")
	w.line("description")
	w.line("  %s;", quote("任务域标记（与华为模型 task-name 语义对齐）：驱动 /yang/modules category 与前端菜单归组。"))
	w.out()
	w.line("}")
	w.blank()
	w.line("%s:task-name %s;", m.prefix, quote(m.taskName))
	w.blank()

	if err := emitObject(w, m.container, &specSchema, "spec"); err != nil {
		return nil, err
	}

	w.out()
	w.line("}")
	return []byte(w.String()), nil
}

// storageVersion returns the unique storage=true version (C2Y-01 负路径：歧义即失败).
func storageVersion(crd *apiextv1.CustomResourceDefinition) (*apiextv1.CustomResourceDefinitionVersion, error) {
	var found *apiextv1.CustomResourceDefinitionVersion
	for i := range crd.Spec.Versions {
		v := &crd.Spec.Versions[i]
		if !v.Storage {
			continue
		}
		if found != nil {
			return nil, fmt.Errorf("multiple storage versions (%s, %s): exactly one storage version is required", found.Name, v.Name)
		}
		found = v
	}
	if found == nil {
		return nil, fmt.Errorf("no storage version found among %d versions: exactly one storage version is required", len(crd.Spec.Versions))
	}
	return found, nil
}

// resolveMeta applies the annotation contract (C2Y-02): revision is mandatory,
// everything else derives deterministically.
func resolveMeta(crd *apiextv1.CustomResourceDefinition) (*meta, error) {
	ann := crd.Annotations
	revision := ann["usmp.io/yang-revision"]
	if revision == "" {
		return nil, fmt.Errorf("annotation usmp.io/yang-revision is required (contract version must be explicit, no implicit dates)")
	}
	if !revisionRe.MatchString(revision) {
		return nil, fmt.Errorf("annotation usmp.io/yang-revision %q must be YYYY-MM-DD", revision)
	}

	singular := crd.Spec.Names.Singular
	if singular == "" {
		singular = strings.ToLower(crd.Spec.Names.Kind)
	}

	m := &meta{
		crdName:   crd.Name,
		revision:  revision,
		module:    ann["usmp.io/yang-module"],
		namespace: ann["usmp.io/yang-namespace"],
		prefix:    ann["usmp.io/yang-prefix"],
		container: ann["usmp.io/yang-container"],
		taskName:  ann["usmp.io/task-name"],
	}
	if m.module == "" {
		m.module = "usmp-" + singular
	}
	if m.namespace == "" {
		m.namespace = "urn:usmp:yang:" + m.module
	}
	if m.prefix == "" {
		for _, seg := range strings.Split(m.module, "-") {
			if seg != "" {
				m.prefix += string(seg[0])
			}
		}
	}
	if m.container == "" {
		m.container = singular
	}
	if m.taskName == "" {
		m.taskName = "business-network"
	}
	// 固定顺序校验（确定性报错）；标识符规则含 RFC7950 xml 前缀禁令。
	for _, c := range []struct{ what, v string }{
		{"module", m.module}, {"prefix", m.prefix}, {"container", m.container},
	} {
		if err := validIdentifier(c.v, "derived "+c.what); err != nil {
			return nil, err
		}
	}
	return m, nil
}
