// Code generated by yanggen. DO NOT EDIT.
// Package gentest 由 yanggen（retire-ygot-runtime）自 YANG 模型生成：
//   - usmp-test
//   - usmp-test-ext
//
// 结构约定冻结见 openspec/changes/retire-ygot-runtime/codegen-conventions.md。
package gentest

import (
	"fmt"
	"reflect"

	"github.com/leezesi/usmp/backend/pkg/yang-runtime/object"
)

// Types 是本包全部生成类型的注册表（类型名 → reflect.Type），
// 供 Scheme 注册与结构对拍守护测试消费（替代 ygot SchemaTree 的按名索引）。
var Types = map[string]reflect.Type{
	"Device":                    reflect.TypeOf((*Device)(nil)).Elem(),
	"UsmpTest_Box":              reflect.TypeOf((*UsmpTest_Box)(nil)).Elem(),
	"UsmpTest_Box_Extras":       reflect.TypeOf((*UsmpTest_Box_Extras)(nil)).Elem(),
	"UsmpTest_Box_Feature":      reflect.TypeOf((*UsmpTest_Box_Feature)(nil)).Elem(),
	"UsmpTest_Box_Routes":       reflect.TypeOf((*UsmpTest_Box_Routes)(nil)).Elem(),
	"UsmpTest_Box_Routes_Route": reflect.TypeOf((*UsmpTest_Box_Routes_Route)(nil)).Elem(),
	"UsmpTest_Box_Vlans":        reflect.TypeOf((*UsmpTest_Box_Vlans)(nil)).Elem(),
	"UsmpTest_Box_Vlans_Vlan":   reflect.TypeOf((*UsmpTest_Box_Vlans_Vlan)(nil)).Elem(),
}

// Device represents the /device YANG schema element.
type Device struct {
	Box *UsmpTest_Box `path:"box" module:"usmp-test"`
}

// IsYangObject ensures that Device implements the object.Object interface.
func (*Device) IsYangObject() {}

// UsmpTest_Box represents the /usmp-test/box YANG schema element.
type UsmpTest_Box struct {
	Big      *uint64                 `path:"big" module:"usmp-test"`
	DhcpPool *string                 `path:"dhcp-pool" module:"usmp-test"`
	Extras   *UsmpTest_Box_Extras    `path:"extras" module:"usmp-test-ext"`
	Feature  *UsmpTest_Box_Feature   `path:"feature" module:"usmp-test"`
	Host     *string                 `path:"host" module:"usmp-test"`
	Levels   []uint32                `path:"levels" module:"usmp-test"`
	Mark     object.Empty            `path:"mark" module:"usmp-test"`
	Mode     E_UsmpTest_Box_Mode     `path:"mode" module:"usmp-test"`
	Mtu      *uint16                 `path:"mtu" module:"usmp-test"`
	On       *bool                   `path:"on" module:"usmp-test"`
	Port     UsmpTest_Box_Port_Union `path:"port" module:"usmp-test"`
	Ratio    *float64                `path:"ratio" module:"usmp-test"`
	Routes   *UsmpTest_Box_Routes    `path:"routes" module:"usmp-test"`
	StaticIp *string                 `path:"static-ip" module:"usmp-test"`
	Status   E_UsmpTest_EnableStatus `path:"status" module:"usmp-test"`
	Tags     []string                `path:"tags" module:"usmp-test"`
	Vlans    *UsmpTest_Box_Vlans     `path:"vlans" module:"usmp-test"`
}

// IsYangObject ensures that UsmpTest_Box implements the object.Object interface.
func (*UsmpTest_Box) IsYangObject() {}

// UsmpTest_Box_Extras represents the /usmp-test/box/extras YANG schema element.
type UsmpTest_Box_Extras struct {
	Note *string `path:"note" module:"usmp-test-ext"`
}

// IsYangObject ensures that UsmpTest_Box_Extras implements the object.Object interface.
func (*UsmpTest_Box_Extras) IsYangObject() {}

// UsmpTest_Box_Feature represents the /usmp-test/box/feature YANG schema element.
type UsmpTest_Box_Feature struct {
	Rate *uint32 `path:"rate" module:"usmp-test"`
}

// IsYangObject ensures that UsmpTest_Box_Feature implements the object.Object interface.
func (*UsmpTest_Box_Feature) IsYangObject() {}

// UsmpTest_Box_Routes represents the /usmp-test/box/routes YANG schema element.
type UsmpTest_Box_Routes struct {
	Route map[UsmpTest_Box_Routes_Route_Key]*UsmpTest_Box_Routes_Route `path:"route" module:"usmp-test"`
}

// IsYangObject ensures that UsmpTest_Box_Routes implements the object.Object interface.
func (*UsmpTest_Box_Routes) IsYangObject() {}

// UsmpTest_Box_Routes_Route represents the /usmp-test/box/routes/route YANG schema element.
type UsmpTest_Box_Routes_Route struct {
	Metric *uint32 `path:"metric" module:"usmp-test"`
	Prefix *string `path:"prefix" module:"usmp-test"`
	Vrf    *string `path:"vrf" module:"usmp-test"`
}

// IsYangObject ensures that UsmpTest_Box_Routes_Route implements the object.Object interface.
func (*UsmpTest_Box_Routes_Route) IsYangObject() {}

// ListKeyMap returns the list keys of UsmpTest_Box_Routes_Route（YANG 叶名 → 值）。
func (t *UsmpTest_Box_Routes_Route) ListKeyMap() (map[string]interface{}, error) {
	if t.Vrf == nil {
		return nil, fmt.Errorf("nil value for key Vrf")
	}
	if t.Prefix == nil {
		return nil, fmt.Errorf("nil value for key Prefix")
	}
	return map[string]interface{}{"vrf": *t.Vrf, "prefix": *t.Prefix}, nil
}

// UsmpTest_Box_Routes_Route_Key represents the key for list UsmpTest_Box_Routes_Route of element /usmp-test/box/routes.
type UsmpTest_Box_Routes_Route_Key struct {
	Vrf    string `path:"vrf"`
	Prefix string `path:"prefix"`
}

// ListKeyMap returns the list keys of UsmpTest_Box_Routes_Route_Key（值接收者，无 nil 面）。
func (t UsmpTest_Box_Routes_Route_Key) ListKeyMap() (map[string]interface{}, error) {
	return map[string]interface{}{"vrf": t.Vrf, "prefix": t.Prefix}, nil
}

// UsmpTest_Box_Vlans represents the /usmp-test/box/vlans YANG schema element.
type UsmpTest_Box_Vlans struct {
	Vlan map[uint16]*UsmpTest_Box_Vlans_Vlan `path:"vlan" module:"usmp-test"`
}

// IsYangObject ensures that UsmpTest_Box_Vlans implements the object.Object interface.
func (*UsmpTest_Box_Vlans) IsYangObject() {}

// UsmpTest_Box_Vlans_Vlan represents the /usmp-test/box/vlans/vlan YANG schema element.
type UsmpTest_Box_Vlans_Vlan struct {
	AdminStatus E_UsmpTest_EnableStatus `path:"admin-status" module:"usmp-test"`
	Id          *uint16                 `path:"id" module:"usmp-test"`
	Name        *string                 `path:"name" module:"usmp-test"`
}

// IsYangObject ensures that UsmpTest_Box_Vlans_Vlan implements the object.Object interface.
func (*UsmpTest_Box_Vlans_Vlan) IsYangObject() {}

// ListKeyMap returns the list keys of UsmpTest_Box_Vlans_Vlan（YANG 叶名 → 值）。
func (t *UsmpTest_Box_Vlans_Vlan) ListKeyMap() (map[string]interface{}, error) {
	if t.Id == nil {
		return nil, fmt.Errorf("nil value for key Id")
	}
	return map[string]interface{}{"id": *t.Id}, nil
}

// E_UsmpTest_Box_Mode is a YANG enumerated type.
type E_UsmpTest_Box_Mode int64

// IsYangEnum ensures that E_UsmpTest_Box_Mode implements the object.Enum interface.
func (E_UsmpTest_Box_Mode) IsYangEnum() {}

// EnumMaps returns the generation-wide enum definition map.
func (e E_UsmpTest_Box_Mode) EnumMaps() map[string]map[int64]object.EnumDefinition { return enumMaps }

// String renders e as its YANG value name.
func (e E_UsmpTest_Box_Mode) String() string {
	return object.EnumLogString(e, int64(e), "E_UsmpTest_Box_Mode")
}

const (
	// UsmpTest_Box_Mode_UNSET corresponds to the value UNSET of E_UsmpTest_Box_Mode.
	UsmpTest_Box_Mode_UNSET E_UsmpTest_Box_Mode = 0
	// UsmpTest_Box_Mode_access corresponds to the value access of E_UsmpTest_Box_Mode.
	UsmpTest_Box_Mode_access E_UsmpTest_Box_Mode = 1
	// UsmpTest_Box_Mode_trunk corresponds to the value trunk of E_UsmpTest_Box_Mode.
	UsmpTest_Box_Mode_trunk E_UsmpTest_Box_Mode = 2
)

// E_UsmpTest_EnableStatus is a YANG enumerated type.
type E_UsmpTest_EnableStatus int64

// IsYangEnum ensures that E_UsmpTest_EnableStatus implements the object.Enum interface.
func (E_UsmpTest_EnableStatus) IsYangEnum() {}

// EnumMaps returns the generation-wide enum definition map.
func (e E_UsmpTest_EnableStatus) EnumMaps() map[string]map[int64]object.EnumDefinition {
	return enumMaps
}

// String renders e as its YANG value name.
func (e E_UsmpTest_EnableStatus) String() string {
	return object.EnumLogString(e, int64(e), "E_UsmpTest_EnableStatus")
}

const (
	// UsmpTest_EnableStatus_UNSET corresponds to the value UNSET of E_UsmpTest_EnableStatus.
	UsmpTest_EnableStatus_UNSET E_UsmpTest_EnableStatus = 0
	// UsmpTest_EnableStatus_enable corresponds to the value enable of E_UsmpTest_EnableStatus.
	UsmpTest_EnableStatus_enable E_UsmpTest_EnableStatus = 2
	// UsmpTest_EnableStatus_disable corresponds to the value disable of E_UsmpTest_EnableStatus.
	UsmpTest_EnableStatus_disable E_UsmpTest_EnableStatus = 3
)

// enumMaps 是全包枚举定义表（外层 key 带 E_ 前缀——消费方按
// reflect Type().Name() 查表，失配即静默解码错，勿改口径）。
var enumMaps = map[string]map[int64]object.EnumDefinition{
	"E_UsmpTest_Box_Mode": {
		1: {Name: "access"},
		2: {Name: "trunk"},
	},
	"E_UsmpTest_EnableStatus": {
		2: {Name: "enable"},
		3: {Name: "disable"},
	},
}

// UsmpTest_Box_Port_Union is a YANG union type.
type UsmpTest_Box_Port_Union interface {
	Is_UsmpTest_Box_Port_Union()
}

// UsmpTest_Box_Port_Union_Uint16 wraps a uint16 member of union UsmpTest_Box_Port_Union.
type UsmpTest_Box_Port_Union_Uint16 struct {
	Uint16 uint16
}

// Is_UsmpTest_Box_Port_Union marks UsmpTest_Box_Port_Union_Uint16 as a member of union UsmpTest_Box_Port_Union.
func (*UsmpTest_Box_Port_Union_Uint16) Is_UsmpTest_Box_Port_Union() {}

// UsmpTest_Box_Port_Union_String wraps a string member of union UsmpTest_Box_Port_Union.
type UsmpTest_Box_Port_Union_String struct {
	String string
}

// Is_UsmpTest_Box_Port_Union marks UsmpTest_Box_Port_Union_String as a member of union UsmpTest_Box_Port_Union.
func (*UsmpTest_Box_Port_Union_String) Is_UsmpTest_Box_Port_Union() {}
