apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: usmp-controller-role
rules:
- apiGroups:
  - biz.usmp.io
  resources:
  - businessvlans
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - biz.usmp.io
  resources:
  - businessvlans/finalizers
  verbs:
  - update
- apiGroups:
  - biz.usmp.io
  resources:
  - businessvlans/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - biz.usmp.io
  resources:
  - businessswitches
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - biz.usmp.io
  resources:
  - businessswitches/finalizers
  verbs:
  - update
- apiGroups:
  - biz.usmp.io
  resources:
  - businessswitches/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - biz.usmp.io
  resources:
  - businessinterfaces
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - biz.usmp.io
  resources:
  - businessinterfaces/finalizers
  verbs:
  - update
- apiGroups:
  - biz.usmp.io
  resources:
  - businessinterfaces/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - biz.usmp.io
  resources:
  - businessroutes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - biz.usmp.io
  resources:
  - businessroutes/finalizers
  verbs:
  - update
- apiGroups:
  - biz.usmp.io
  resources:
  - businessroutes/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - biz.usmp.io
  resources:
  - nativedeviceconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - biz.usmp.io
  resources:
  - nativedeviceconfigs/finalizers
  verbs:
  - update
- apiGroups:
  - biz.usmp.io
  resources:
  - nativedeviceconfigs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
