// Code generated by tools/blacklistgen. DO NOT EDIT.
//
// Blacklisted module names from the SND package blacklist.xml whose revision
// matches the in-repo YANG source (CN-03). Annotation only — never used to
// prune the module set.

package yangschema

// BlacklistedModules is the set of top-level container names of SND-blacklisted
// modules (keyed like /yang/modules module names, e.g. "system"),
// revision-matched at generation time.
var BlacklistedModules = map[string]bool{
	"dhcp":                true,
	"dhcpv6":              true,
	"direct-route-vlink":  true,
	"evpl":                true,
	"fwm-resource":        true,
	"ipv6-nd":             true,
	"l2vpn":               true,
	"monitor-group":       true,
	"mpls":                true,
	"pbr":                 true,
	"pki":                 true,
	"qos-bd":              true,
	"rgm":                 true,
	"route-monitor-group": true,
	"sshc":                true,
	"sshs":                true,
	"ssl":                 true,
	"system":              true,
	"traffic-analysis":    true,
	"xpl":                 true,
}
