// Code generated by tools/lefttreegen. DO NOT EDIT.
//
// SND left-tree（LT-01）：分组层级 + 双语名 + 叶子源模块与顶层数据容器映射。
// 运行期零 snd 文件依赖；升级 snd 包后重跑 go:generate。

package yangschema

// LeftTreeNode 是左树节点：分组（Children 非空）或叶子（SourceModule 非空）。
type LeftTreeNode struct {
	Zh             string
	En             string
	SourceModule   string
	RootContainers []string
	Children       []LeftTreeNode
}

// LeftTree 是完整 SND 左树。
var LeftTree = []LeftTreeNode{
	{Zh: "基础配置", En: "Basic Configuration", Children: []LeftTreeNode{
		{Zh: "登录设备命令行界面", En: "CLI-based Device Login", Children: []LeftTreeNode{
			{Zh: "huawei-dsa", En: "huawei-dsa", SourceModule: "huawei-dsa", RootContainers: []string{"dsa"}},
			{Zh: "huawei-ecc", En: "huawei-ecc", SourceModule: "huawei-ecc", RootContainers: []string{"ecc"}},
			{Zh: "huawei-rsa", En: "huawei-rsa", SourceModule: "huawei-rsa", RootContainers: []string{"rsa"}},
			{Zh: "huawei-vty", En: "huawei-vty", SourceModule: "huawei-vty", RootContainers: []string{"vty"}},
		}},
		{Zh: "文件系统管理", En: "File System Management", Children: []LeftTreeNode{
			{Zh: "huawei-ftpc", En: "huawei-ftpc", SourceModule: "huawei-ftpc", RootContainers: []string{"ftpc"}},
		}},
		{Zh: "配置文件管理", En: "Configuration File Management", Children: []LeftTreeNode{
			{Zh: "huawei-cfg", En: "huawei-cfg", SourceModule: "huawei-cfg", RootContainers: []string{"cfg"}},
		}},
	}},
	{Zh: "以太网交换", En: "Ethernet Switching", Children: []LeftTreeNode{
		{Zh: "VLAN", En: "VLAN", Children: []LeftTreeNode{
			{Zh: "huawei-vlan", En: "huawei-vlan", SourceModule: "huawei-vlan", RootContainers: []string{"vlan"}},
			{Zh: "huawei-ethernet", En: "huawei-ethernet", SourceModule: "huawei-ethernet"},
			{Zh: "huawei-bd", En: "huawei-bd", SourceModule: "huawei-bd", RootContainers: []string{"bd"}},
		}},
		{Zh: "MAC", En: "MAC", Children: []LeftTreeNode{
			{Zh: "huawei-mac-flapping-detect", En: "huawei-mac-flapping-detect", SourceModule: "huawei-mac-flapping-detect", RootContainers: []string{"mac-flapping-detect"}},
		}},
		{Zh: "Eth-Trunk", En: "Eth-Trunk", Children: []LeftTreeNode{
			{Zh: "huawei-ifm-trunk", En: "huawei-ifm-trunk", SourceModule: "huawei-ifm-trunk", RootContainers: []string{"ifm-trunk"}},
			{Zh: "huawei-lacp", En: "huawei-lacp", SourceModule: "huawei-lacp", RootContainers: []string{"lacp"}},
		}},
		{Zh: "STP_RSTP_MSTP", En: "STP_RSTP_MSTP", Children: []LeftTreeNode{
			{Zh: "huawei-mstp", En: "huawei-mstp", SourceModule: "huawei-mstp", RootContainers: []string{"mstp"}},
		}},
	}},
	{Zh: "可靠性", En: "High Availability", Children: []LeftTreeNode{
		{Zh: "BFD", En: "BFD", Children: []LeftTreeNode{
			{Zh: "huawei-bfd", En: "huawei-bfd", SourceModule: "huawei-bfd", RootContainers: []string{"bfd"}},
		}},
		{Zh: "M-LAG", En: "M-LAG", Children: []LeftTreeNode{
			{Zh: "huawei-m-lag", En: "huawei-m-lag", SourceModule: "huawei-m-lag", RootContainers: []string{"m-lag"}},
		}},
		{Zh: "VRRP", En: "VRRP", Children: []LeftTreeNode{
			{Zh: "huawei-vrrp", En: "huawei-vrrp", SourceModule: "huawei-vrrp", RootContainers: []string{"vrrp"}},
		}},
		{Zh: "Monitor Link", En: "Monitor Link", Children: []LeftTreeNode{
			{Zh: "huawei-monitor-link", En: "huawei-monitor-link", SourceModule: "huawei-monitor-link", RootContainers: []string{"monitor-link"}},
		}},
	}},
	{Zh: "系统监控", En: "System Monitor", Children: []LeftTreeNode{
		{Zh: "NQA", En: "NQA", Children: []LeftTreeNode{
			{Zh: "huawei-nqa", En: "huawei-nqa", SourceModule: "huawei-nqa", RootContainers: []string{"nqa"}},
		}},
		{Zh: "镜像", En: "Mirroring", Children: []LeftTreeNode{
			{Zh: "huawei-mirror", En: "huawei-mirror", SourceModule: "huawei-mirror", RootContainers: []string{"mirror"}},
		}},
		{Zh: "路径/连通性探测", En: "Path and Connectivity Detection", Children: []LeftTreeNode{
			{Zh: "huawei-vxlan-path-detect", En: "huawei-vxlan-path-detect", SourceModule: "huawei-vxlan-path-detect", RootContainers: []string{"vxlan-path-detect"}},
		}},
		{Zh: "gRPC", En: "gRPC", Children: []LeftTreeNode{
			{Zh: "huawei-grpc", En: "huawei-grpc", SourceModule: "huawei-grpc", RootContainers: []string{"grpc"}},
		}},
		{Zh: "全流分析", En: "AnyFlow", Children: []LeftTreeNode{
			{Zh: "huawei-anyflow", En: "huawei-anyflow", SourceModule: "huawei-anyflow", RootContainers: []string{"anyflow"}},
		}},
		{Zh: "智能流量分析", En: "Intelligent Traffic Analysis", Children: []LeftTreeNode{
			{Zh: "huawei-analysis-collector", En: "huawei-analysis-collector", SourceModule: "huawei-analysis-collector", RootContainers: []string{"analysis-collector"}},
		}},
		{Zh: "Packet Event", En: "Packet Event", Children: []LeftTreeNode{
			{Zh: "huawei-packetevent", En: "huawei-packetevent", SourceModule: "huawei-packetevent", RootContainers: []string{"packetevent"}},
		}},
		{Zh: "sFlow", En: "sFlow", Children: []LeftTreeNode{
			{Zh: "huawei-sflow", En: "huawei-sflow", SourceModule: "huawei-sflow", RootContainers: []string{"sflow"}},
		}},
		{Zh: "Telemetry", En: "Telemetry", Children: []LeftTreeNode{
			{Zh: "openconfig-telemetry", En: "openconfig-telemetry", SourceModule: "openconfig-telemetry", RootContainers: []string{"telemetry-system"}},
		}},
	}},
	{Zh: "IP路由", En: "IP Routing", Children: []LeftTreeNode{
		{Zh: "OSPF", En: "OSPF", Children: []LeftTreeNode{
			{Zh: "huawei-ospfv2", En: "huawei-ospfv2", SourceModule: "huawei-ospfv2", RootContainers: []string{"ospfv2"}},
			{Zh: "huawei-ospfv3", En: "huawei-ospfv3", SourceModule: "huawei-ospfv3", RootContainers: []string{"ospfv3"}},
		}},
		{Zh: "路由管理", En: "Route Management", Children: []LeftTreeNode{
			{Zh: "huawei-fib", En: "huawei-fib", SourceModule: "huawei-fib", RootContainers: []string{"fib"}},
			{Zh: "huawei-routing", En: "huawei-routing", SourceModule: "huawei-routing", RootContainers: []string{"routing"}},
		}},
		{Zh: "BGP", En: "BGP", Children: []LeftTreeNode{
			{Zh: "huawei-bgp", En: "huawei-bgp", SourceModule: "huawei-bgp", RootContainers: []string{"bgp"}},
		}},
		{Zh: "路由策略", En: "Routing Policy", Children: []LeftTreeNode{
			{Zh: "huawei-routing-policy", En: "huawei-routing-policy", SourceModule: "huawei-routing-policy", RootContainers: []string{"routing-policy"}},
		}},
	}},
	{Zh: "接口管理", En: "Interface Management", Children: []LeftTreeNode{
		{Zh: "接口基础", En: "Interface Basic", Children: []LeftTreeNode{
			{Zh: "huawei-ifm", En: "huawei-ifm", SourceModule: "huawei-ifm", RootContainers: []string{"ifm"}},
		}},
		{Zh: "以太网接口", En: "Ethernet Interface", Children: []LeftTreeNode{
			{Zh: "huawei-pic", En: "huawei-pic", SourceModule: "huawei-pic", RootContainers: []string{"pic"}},
		}},
	}},
	{Zh: "系统管理", En: "System Management", Children: []LeftTreeNode{
		{Zh: "硬件管理", En: "Hardware Management", Children: []LeftTreeNode{
			{Zh: "huawei-devm", En: "huawei-devm", SourceModule: "huawei-devm", RootContainers: []string{"devm"}},
			{Zh: "huawei-driver", En: "huawei-driver", SourceModule: "huawei-driver", RootContainers: []string{"driver"}},
		}},
		{Zh: "信息管理", En: "Information Management", Children: []LeftTreeNode{
			{Zh: "huawei-syslog", En: "huawei-syslog", SourceModule: "huawei-syslog", RootContainers: []string{"syslog"}},
		}},
		{Zh: "NTP", En: "NTP", Children: []LeftTreeNode{
			{Zh: "huawei-ntp", En: "huawei-ntp", SourceModule: "huawei-ntp", RootContainers: []string{"ntp"}},
		}},
		{Zh: "LLDP", En: "LLDP", Children: []LeftTreeNode{
			{Zh: "huawei-lldp", En: "huawei-lldp", SourceModule: "huawei-lldp", RootContainers: []string{"lldp"}},
		}},
		{Zh: "SNMP", En: "SNMP", Children: []LeftTreeNode{
			{Zh: "huawei-snmp", En: "huawei-snmp", SourceModule: "huawei-snmp", RootContainers: []string{"snmp"}},
		}},
		{Zh: "OpenFlow", En: "OpenFlow", Children: []LeftTreeNode{
			{Zh: "huawei-openflow-agent", En: "huawei-openflow-agent", SourceModule: "huawei-openflow-agent", RootContainers: []string{"openflow-agent"}},
		}},
		{Zh: "升级维护", En: "Upgrade Maintenance", Children: []LeftTreeNode{
			{Zh: "huawei-license", En: "huawei-license", SourceModule: "huawei-license", RootContainers: []string{"license"}},
			{Zh: "huawei-system-resources-usage", En: "huawei-system-resources-usage", SourceModule: "huawei-system-resources-usage", RootContainers: []string{"system-resources-usage"}},
		}},
	}},
	{Zh: "安全", En: "Security", Children: []LeftTreeNode{
		{Zh: "MACsec", En: "MACsec", Children: []LeftTreeNode{
			{Zh: "huawei-macsec", En: "huawei-macsec", SourceModule: "huawei-macsec", RootContainers: []string{"macsec"}},
		}},
		{Zh: "SSH", En: "SSH", Children: []LeftTreeNode{
			{Zh: "huawei-sm2", En: "huawei-sm2", SourceModule: "huawei-sm2", RootContainers: []string{"sm2"}},
		}},
		{Zh: "微分段", En: "Microsegmentation", Children: []LeftTreeNode{
			{Zh: "huawei-microsegmentation", En: "huawei-microsegmentation", SourceModule: "huawei-microsegmentation", RootContainers: []string{"microsegmentation"}},
		}},
	}},
	{Zh: "IP地址与服务", En: "IP Addresses and Services", Children: []LeftTreeNode{
		{Zh: "IPv4基础", En: "IPv4 Basic", Children: []LeftTreeNode{
			{Zh: "huawei-unicast-forward", En: "huawei-unicast-forward", SourceModule: "huawei-unicast-forward", RootContainers: []string{"unicast-forward"}},
			{Zh: "huawei-ip", En: "huawei-ip", SourceModule: "huawei-ip"},
		}},
		{Zh: "负载分担", En: "Load Balancing", Children: []LeftTreeNode{
			{Zh: "huawei-loadbalance", En: "huawei-loadbalance", SourceModule: "huawei-loadbalance", RootContainers: []string{"loadbalance"}},
		}},
		{Zh: "ARP", En: "ARP", Children: []LeftTreeNode{
			{Zh: "huawei-arp", En: "huawei-arp", SourceModule: "huawei-arp", RootContainers: []string{"arp"}},
		}},
		{Zh: "ACL", En: "ACL", Children: []LeftTreeNode{
			{Zh: "huawei-acl", En: "huawei-acl", SourceModule: "huawei-acl", RootContainers: []string{"acl"}},
			{Zh: "huawei-time-range", En: "huawei-time-range", SourceModule: "huawei-time-range", RootContainers: []string{"time-range"}},
		}},
	}},
	{Zh: "IP组播", En: "IP Multicast", Children: []LeftTreeNode{
		{Zh: "IPv4组播路由管理", En: "IPv4 Multicast Route Management", Children: []LeftTreeNode{
			{Zh: "huawei-l3-multicast", En: "huawei-l3-multicast", SourceModule: "huawei-l3-multicast", RootContainers: []string{"l3-multicast"}},
			{Zh: "huawei-multicast", En: "huawei-multicast", SourceModule: "huawei-multicast", RootContainers: []string{"multicast"}},
		}},
		{Zh: "IPv4三层组播Over VXLAN", En: "IPv4 Layer 3 Multicast over VXLAN", Children: []LeftTreeNode{
			{Zh: "huawei-mvpn", En: "huawei-mvpn", SourceModule: "huawei-mvpn", RootContainers: []string{"mvpn"}},
		}},
	}},
	{Zh: "VPN", En: "VPN", Children: []LeftTreeNode{
		{Zh: "GRE", En: "GRE", Children: []LeftTreeNode{
			{Zh: "huawei-gre", En: "huawei-gre", SourceModule: "huawei-gre"},
		}},
		{Zh: "IPv4 L3VPN", En: "IPv4 L3VPN", Children: []LeftTreeNode{
			{Zh: "huawei-l3vpn", En: "huawei-l3vpn", SourceModule: "huawei-l3vpn", RootContainers: []string{"l3vpn"}},
			{Zh: "huawei-network-instance", En: "huawei-network-instance", SourceModule: "huawei-network-instance", RootContainers: []string{"network-instance"}},
		}},
		{Zh: "隧道管理", En: "Tunnel Management", Children: []LeftTreeNode{
			{Zh: "huawei-tunnel-management", En: "huawei-tunnel-management", SourceModule: "huawei-tunnel-management", RootContainers: []string{"tunnel-management"}},
		}},
		{Zh: "EVPN", En: "EVPN", Children: []LeftTreeNode{
			{Zh: "huawei-evpn", En: "huawei-evpn", SourceModule: "huawei-evpn", RootContainers: []string{"evpn"}},
		}},
	}},
	{Zh: "VXLAN", En: "VXLAN", Children: []LeftTreeNode{
		{Zh: "VXLAN", En: "VXLAN", Children: []LeftTreeNode{
			{Zh: "huawei-vxlan-ext", En: "huawei-vxlan-ext", SourceModule: "huawei-vxlan-ext", RootContainers: []string{"vxlan-ext"}},
			{Zh: "huawei-nvo3", En: "huawei-nvo3", SourceModule: "huawei-nvo3", RootContainers: []string{"nvo3"}},
			{Zh: "huawei-nvo3-statistics", En: "huawei-nvo3-statistics", SourceModule: "huawei-nvo3-statistics"},
		}},
	}},
	{Zh: "用户接入与认证", En: "User Access and Authentication", Children: []LeftTreeNode{
		{Zh: "AAA", En: "AAA", Children: []LeftTreeNode{
			{Zh: "huawei-hwtacacs", En: "huawei-hwtacacs", SourceModule: "huawei-hwtacacs", RootContainers: []string{"hwtacacs"}},
		}},
	}},
	{Zh: "QOS", En: "QOS", Children: []LeftTreeNode{
		{Zh: "QOS", En: "QOS", Children: []LeftTreeNode{
			{Zh: "huawei-qos", En: "huawei-qos", SourceModule: "huawei-qos", RootContainers: []string{"qos"}},
		}},
	}},
}
