// Code generated by tools/rpcgen. DO NOT EDIT.
//
// YANG rpc 定义（RPC-01）：模块 → rpc（名称/高危/输入叶）。ygot 运行期 schema
// 不含 rpc，构建期以 goyang 提取；运行期零 snd 文件依赖，升级 snd 后重跑 go:generate。

package yangschema

// RPCInputLeaf 是一个 rpc 输入叶（运行期映射为前端 FieldDef，RPC-02）。
type RPCInputLeaf struct {
	Name      string
	Type      string
	LeafRef   string
	Mandatory bool
	Units     string
	Pattern   string
}

// RPCDef 是一个 rpc：名称、高危标记（RPC-04）、输入叶。
type RPCDef struct {
	Name     string
	HighRisk bool
	Input    []RPCInputLeaf
}

// ModuleRPCs 是各模块的 rpc 定义（键为模块根容器名，与 schema 一致）。
var ModuleRPCs = map[string][]RPCDef{
	"arp": {
		{Name: "batch-delete-all", HighRisk: true},
		{Name: "batch-delete-vpn", HighRisk: true, Input: []RPCInputLeaf{
			{Name: "ni-name", Type: "leafref", LeafRef: "/arp:arp/arp:static-arps/arp:static-arp/arp:ni-name"},
		}},
		{Name: "convert-to-static", HighRisk: false, Input: []RPCInputLeaf{
			{Name: "if-name", Type: "leafref", LeafRef: "/arp:arp/arp:query-entries/arp:query-entry/arp:if-name"},
		}},
	},
	"cfg": {
		{Name: "cfg-file-backup-and-recovery", HighRisk: false, Input: []RPCInputLeaf{
			{Name: "filename", Type: "string"},
			{Name: "index", Type: "number", Mandatory: true},
			{Name: "operation-type", Type: "enum", Mandatory: true},
			{Name: "password", Type: "string"},
			{Name: "server-ip", Type: "string", Mandatory: true},
			{Name: "transport-type", Type: "enum", Mandatory: true},
			{Name: "use-net-manager-vpn", Type: "boolean"},
			{Name: "username", Type: "string"},
			{Name: "vpn-instance", Type: "string"},
		}},
		{Name: "clear-interface-config", HighRisk: false, Input: []RPCInputLeaf{
			{Name: "interface-name", Type: "leafref", LeafRef: "/ifm:ifm/ifm:interfaces/ifm:interface/ifm:name", Mandatory: true},
		}},
		{Name: "clear-startup", HighRisk: false},
		{Name: "config-recovery-by-time", HighRisk: false, Input: []RPCInputLeaf{
			{Name: "auto-backup-time", Type: "string", Mandatory: true, Pattern: "\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}(\\.\\d+)?(Z|[\\+\\-]\\d{2}:\\d{2})"},
		}},
		{Name: "create-user-label-checkpoint", HighRisk: false, Input: []RPCInputLeaf{
			{Name: "description", Type: "string"},
			{Name: "user-label", Type: "string", Mandatory: true, Pattern: ".*[^\\s]+.*"},
		}},
		{Name: "delete-checkpoint-by-oldest-num", HighRisk: true, Input: []RPCInputLeaf{
			{Name: "checkpoint-num", Type: "number"},
		}},
		{Name: "delete-startup", HighRisk: true},
		{Name: "delete-startup-reserved-dcn", HighRisk: true},
		{Name: "delete-user-label-checkpoint", HighRisk: true, Input: []RPCInputLeaf{
			{Name: "commit-id", Type: "leafref", LeafRef: "/cfg:cfg/cfg:checkpoints/cfg:checkpoint/cfg:commit-id"},
		}},
		{Name: "reset-user-label-by-commit-id", HighRisk: false, Input: []RPCInputLeaf{
			{Name: "commit-id", Type: "leafref", LeafRef: "/cfg:cfg/cfg:checkpoints/cfg:checkpoint/cfg:commit-id", Mandatory: true},
		}},
		{Name: "rollback-by-commit-id", HighRisk: true, Input: []RPCInputLeaf{
			{Name: "commit-id", Type: "leafref", LeafRef: "/cfg:cfg/cfg:checkpoints/cfg:checkpoint/cfg:commit-id"},
		}},
		{Name: "rollback-by-file", HighRisk: true, Input: []RPCInputLeaf{
			{Name: "filename", Type: "leafref", LeafRef: "/cfg:cfg/cfg:cfg-files/cfg:cfg-file/cfg:filename", Mandatory: true},
		}},
		{Name: "rollback-by-last-num", HighRisk: true, Input: []RPCInputLeaf{
			{Name: "checkpoint-num", Type: "number"},
		}},
		{Name: "rollback-by-user-label", HighRisk: true, Input: []RPCInputLeaf{
			{Name: "commit-id", Type: "leafref", LeafRef: "/cfg:cfg/cfg:checkpoints/cfg:checkpoint/cfg:commit-id"},
			{Name: "user-label", Type: "leafref", LeafRef: "/cfg:cfg/cfg:checkpoints/cfg:checkpoint/cfg:user-label"},
		}},
		{Name: "save", HighRisk: false, Input: []RPCInputLeaf{
			{Name: "filename", Type: "string", Mandatory: true},
		}},
		{Name: "save-all-virtual-systems", HighRisk: false},
		{Name: "set-startup", HighRisk: false, Input: []RPCInputLeaf{
			{Name: "filename", Type: "leafref", LeafRef: "/cfg:cfg/cfg:cfg-files/cfg:cfg-file/cfg:filename", Mandatory: true},
		}},
		{Name: "set-user-label-by-commit-id", HighRisk: false, Input: []RPCInputLeaf{
			{Name: "commit-id", Type: "leafref", LeafRef: "/cfg:cfg/cfg:checkpoints/cfg:checkpoint/cfg:commit-id", Mandatory: true},
			{Name: "user-label", Type: "string", Mandatory: true, Pattern: ".*[^\\s]+.*"},
		}},
		{Name: "specify-slot-set-startup", HighRisk: false, Input: []RPCInputLeaf{
			{Name: "filename", Type: "leafref", LeafRef: "/cfg:cfg/cfg:cfg-files/cfg:cfg-file/cfg:filename", Mandatory: true},
			{Name: "position", Type: "leafref", LeafRef: "/devm:devm/devm:mpu-boards/devm:mpu-board/devm:position"},
		}},
	},
	"devm": {
		{Name: "clear-inactive-config", HighRisk: false, Input: []RPCInputLeaf{
			{Name: "entity-class", Type: "enum", Mandatory: true},
			{Name: "position", Type: "string", Mandatory: true},
		}},
		{Name: "cold-reset-lpu", HighRisk: true, Input: []RPCInputLeaf{
			{Name: "board-position", Type: "string", Mandatory: true},
		}},
		{Name: "cold-reset-mpu", HighRisk: true, Input: []RPCInputLeaf{
			{Name: "board-position", Type: "string", Mandatory: true},
		}},
		{Name: "reboot", HighRisk: true, Input: []RPCInputLeaf{
			{Name: "save-flag", Type: "boolean"},
		}},
		{Name: "reset-board", HighRisk: false, Input: []RPCInputLeaf{
			{Name: "board-position", Type: "string", Mandatory: true},
		}},
		{Name: "reset-card", HighRisk: false, Input: []RPCInputLeaf{
			{Name: "card-position", Type: "string", Mandatory: true},
		}},
		{Name: "reset-lpu-board", HighRisk: false, Input: []RPCInputLeaf{
			{Name: "board-position", Type: "string", Mandatory: true},
		}},
		{Name: "reset-mpu-board", HighRisk: false, Input: []RPCInputLeaf{
			{Name: "board-position", Type: "string", Mandatory: true},
		}},
		{Name: "reset-offline-config", HighRisk: false, Input: []RPCInputLeaf{
			{Name: "board-position", Type: "string", Mandatory: true},
		}},
		{Name: "reset-sfu-board", HighRisk: false, Input: []RPCInputLeaf{
			{Name: "board-position", Type: "string", Mandatory: true},
		}},
		{Name: "schedule-reboot-at-time", HighRisk: true, Input: []RPCInputLeaf{
			{Name: "save-flag", Type: "boolean"},
			{Name: "schedule-date", Type: "string", Mandatory: true, Pattern: "\\d{4}-\\d{2}-\\d{2}"},
			{Name: "schedule-datetime", Type: "string", Mandatory: true, Pattern: "(([0-1][0-9])|(2[0-3])|[0-9]):([0-5][0-9]|[0-9])"},
		}},
		{Name: "schedule-reboot-delay-time", HighRisk: true, Input: []RPCInputLeaf{
			{Name: "delay-time", Type: "string", Mandatory: true},
			{Name: "save-flag", Type: "boolean"},
		}},
		{Name: "transfer-pnpp", HighRisk: false, Input: []RPCInputLeaf{
			{Name: "command-type", Type: "enum"},
			{Name: "local-file-name", Type: "string"},
			{Name: "password", Type: "string", Mandatory: true},
			{Name: "remote-extension", Type: "string"},
			{Name: "remote-file-name", Type: "string"},
			{Name: "server-ip-address", Type: "string", Mandatory: true},
			{Name: "server-port", Type: "number"},
			{Name: "server-type", Type: "enum"},
			{Name: "source-interface-name", Type: "string"},
			{Name: "source-ipv4-address", Type: "string", Pattern: "(([0-9]|[1-9][0-9]|1[0-9][0-9]|2[0-4][0-9]|25[0-5])\\.){3}([0-9]|[1-9][0-9]|1[0-9][0-9]|2[0-4][0-9]|25[0-5])(%[\\p{N}\\p{L}]+)?"},
			{Name: "user-name", Type: "string", Mandatory: true},
			{Name: "vpn-instance-name", Type: "string"},
		}},
		{Name: "undo-schedule-reboot", HighRisk: true},
		{Name: "warm-reset-lpu", HighRisk: true, Input: []RPCInputLeaf{
			{Name: "board-position", Type: "string", Mandatory: true},
		}},
		{Name: "warm-reset-mpu", HighRisk: true, Input: []RPCInputLeaf{
			{Name: "board-position", Type: "string", Mandatory: true},
		}},
	},
	"driver": {
		{Name: "auto-upgrade-models", HighRisk: true, Input: []RPCInputLeaf{
			{Name: "auto-upgrade-model", Type: "enum"},
		}},
		{Name: "board-channel-check", HighRisk: false, Input: []RPCInputLeaf{
			{Name: "enable", Type: "enum", Mandatory: true},
		}},
		{Name: "check-hardware-compatibility", HighRisk: false},
		{Name: "check-hardware-version", HighRisk: false, Input: []RPCInputLeaf{
			{Name: "chassis-id", Type: "string"},
		}},
		{Name: "check-lcm-channel", HighRisk: false},
		{Name: "check-system-software", HighRisk: false},
		{Name: "clear-nv-port-bip8-err-alarm", HighRisk: false, Input: []RPCInputLeaf{
			{Name: "if-name", Type: "leafref", LeafRef: "/ifm:ifm/ifm:interfaces/ifm:interface/ifm:name"},
		}},
		{Name: "clear-nv-port-crc-err-alarm", HighRisk: false, Input: []RPCInputLeaf{
			{Name: "if-name", Type: "leafref", LeafRef: "/ifm:ifm/ifm:interfaces/ifm:interface/ifm:name"},
		}},
		{Name: "clear-nv-port-input-err-alarm", HighRisk: false, Input: []RPCInputLeaf{
			{Name: "if-name", Type: "leafref", LeafRef: "/ifm:ifm/ifm:interfaces/ifm:interface/ifm:name"},
		}},
		{Name: "clear-nv-port-output-err-alarm", HighRisk: false, Input: []RPCInputLeaf{
			{Name: "if-name", Type: "leafref", LeafRef: "/ifm:ifm/ifm:interfaces/ifm:interface/ifm:name"},
		}},
		{Name: "clear-nv-port-sdh-err-alarm", HighRisk: false, Input: []RPCInputLeaf{
			{Name: "if-name", Type: "leafref", LeafRef: "/ifm:ifm/ifm:interfaces/ifm:interface/ifm:name"},
		}},
		{Name: "clear-nv-port-symbol-err-alarm", HighRisk: false, Input: []RPCInputLeaf{
			{Name: "if-name", Type: "leafref", LeafRef: "/ifm:ifm/ifm:interfaces/ifm:interface/ifm:name"},
		}},
		{Name: "clear-nv-port-trans-alarm", HighRisk: false, Input: []RPCInputLeaf{
			{Name: "if-name", Type: "leafref", LeafRef: "/ifm:ifm/ifm:interfaces/ifm:interface/ifm:name"},
		}},
		{Name: "clear-nv-port-tx-pause-err-alarm", HighRisk: false, Input: []RPCInputLeaf{
			{Name: "if-name", Type: "leafref", LeafRef: "/ifm:ifm/ifm:interfaces/ifm:interface/ifm:name"},
		}},
		{Name: "clear-port-bip8-err-alarm", HighRisk: false, Input: []RPCInputLeaf{
			{Name: "port-position", Type: "leafref", LeafRef: "/devm:devm/devm:ports/devm:port/devm:position"},
		}},
		{Name: "clear-port-tx-pause-err-alarm", HighRisk: false, Input: []RPCInputLeaf{
			{Name: "port-position", Type: "leafref", LeafRef: "/devm:devm/devm:ports/devm:port/devm:position"},
		}},
		{Name: "interface-match-check-recovery", HighRisk: false, Input: []RPCInputLeaf{
			{Name: "position", Type: "string"},
		}},
		{Name: "multi-level-alarm-boolean", HighRisk: false, Input: []RPCInputLeaf{
			{Name: "alarm-level", Type: "enum"},
			{Name: "index", Type: "string", Mandatory: true},
			{Name: "operation-flag", Type: "enum", Mandatory: true},
			{Name: "relation", Type: "enum"},
			{Name: "slot", Type: "string", Mandatory: true},
		}},
		{Name: "power-off-card", HighRisk: true, Input: []RPCInputLeaf{
			{Name: "auto-power-on", Type: "string"},
			{Name: "card-position", Type: "leafref", LeafRef: "/devm:devm/devm:cards/devm:card/devm:position", Mandatory: true},
		}},
		{Name: "power-off-ecu", HighRisk: true, Input: []RPCInputLeaf{
			{Name: "auto-power-on", Type: "string"},
			{Name: "board-position", Type: "string", Mandatory: true},
		}},
		{Name: "power-off-icu", HighRisk: true, Input: []RPCInputLeaf{
			{Name: "auto-power-on", Type: "string"},
			{Name: "board-position", Type: "leafref", LeafRef: "/devm:devm/driver:driver/driver:icus/driver:icu/driver:position", Mandatory: true},
		}},
		{Name: "power-off-lpu", HighRisk: true, Input: []RPCInputLeaf{
			{Name: "auto-power-on", Type: "string"},
			{Name: "board-position", Type: "leafref", LeafRef: "/devm:devm/devm:lpu-boards/devm:lpu-board/devm:position", Mandatory: true},
		}},
		{Name: "power-off-mpu", HighRisk: true, Input: []RPCInputLeaf{
			{Name: "auto-power-on", Type: "string"},
			{Name: "board-position", Type: "leafref", LeafRef: "/devm:devm/devm:mpu-boards/devm:mpu-board/devm:position", Mandatory: true},
		}},
		{Name: "power-off-sfu", HighRisk: true, Input: []RPCInputLeaf{
			{Name: "auto-power-on", Type: "string"},
			{Name: "board-position", Type: "leafref", LeafRef: "/devm:devm/devm:sfu-boards/devm:sfu-board/devm:position", Mandatory: true},
		}},
		{Name: "power-on-card", HighRisk: true, Input: []RPCInputLeaf{
			{Name: "card-position", Type: "leafref", LeafRef: "/devm:devm/devm:cards/devm:card/devm:position", Mandatory: true},
		}},
		{Name: "power-on-ecu", HighRisk: true, Input: []RPCInputLeaf{
			{Name: "board-position", Type: "string", Mandatory: true},
		}},
		{Name: "power-on-icu", HighRisk: true, Input: []RPCInputLeaf{
			{Name: "board-position", Type: "leafref", LeafRef: "/devm:devm/driver:driver/driver:icus/driver:icu/driver:position", Mandatory: true},
		}},
		{Name: "power-on-lpu", HighRisk: true, Input: []RPCInputLeaf{
			{Name: "board-position", Type: "leafref", LeafRef: "/devm:devm/devm:lpu-boards/devm:lpu-board/devm:position", Mandatory: true},
		}},
		{Name: "power-on-mpu", HighRisk: true, Input: []RPCInputLeaf{
			{Name: "board-position", Type: "leafref", LeafRef: "/devm:devm/devm:mpu-boards/devm:mpu-board/devm:position", Mandatory: true},
		}},
		{Name: "power-on-sfu", HighRisk: true, Input: []RPCInputLeaf{
			{Name: "board-position", Type: "leafref", LeafRef: "/devm:devm/devm:sfu-boards/devm:sfu-board/devm:position", Mandatory: true},
		}},
		{Name: "reset-cmu-board", HighRisk: false, Input: []RPCInputLeaf{
			{Name: "board-position", Type: "leafref", LeafRef: "/devm:devm/driver:driver/driver:cmus/driver:cmu/driver:position"},
		}},
		{Name: "reset-dustproof-net", HighRisk: false, Input: []RPCInputLeaf{
			{Name: "chassis-position", Type: "leafref", LeafRef: "/devm:devm/devm:chassiss/devm:chassis/devm:position"},
		}},
		{Name: "reset-ecu-board", HighRisk: false, Input: []RPCInputLeaf{
			{Name: "board-position", Type: "string"},
		}},
		{Name: "reset-fan-board", HighRisk: false, Input: []RPCInputLeaf{
			{Name: "board-position", Type: "leafref", LeafRef: "/devm:devm/driver:driver/driver:fans/driver:fan/driver:position"},
		}},
		{Name: "reset-icu-board", HighRisk: false, Input: []RPCInputLeaf{
			{Name: "board-position", Type: "leafref", LeafRef: "/devm:devm/driver:driver/driver:icus/driver:icu/driver:position"},
		}},
		{Name: "reset-lcd", HighRisk: false, Input: []RPCInputLeaf{
			{Name: "board-position", Type: "string"},
		}},
		{Name: "reset-mbus-node", HighRisk: false, Input: []RPCInputLeaf{
			{Name: "board-position", Type: "leafref", LeafRef: "/driver:driver/driver:mbusnodes/driver:mbusnode/driver:slot-id"},
		}},
		{Name: "rollback", HighRisk: true, Input: []RPCInputLeaf{
			{Name: "rollback-choice", Type: "enum"},
		}},
		{Name: "set-boot-password", HighRisk: false, Input: []RPCInputLeaf{
			{Name: "new-password", Type: "string", Mandatory: true},
			{Name: "old-password", Type: "string"},
			{Name: "slot-id", Type: "string", Mandatory: true},
		}},
		{Name: "set-chassis-run-mode", HighRisk: false, Input: []RPCInputLeaf{
			{Name: "chassis-id", Type: "string"},
			{Name: "next-run-cluster", Type: "string"},
			{Name: "next-run-mode", Type: "enum", Mandatory: true},
		}},
		{Name: "set-flash-lock", HighRisk: false, Input: []RPCInputLeaf{
			{Name: "days", Type: "number"},
			{Name: "flash-lock", Type: "enum"},
		}},
		{Name: "set-led-flash", HighRisk: false, Input: []RPCInputLeaf{
			{Name: "alarm-status-time", Type: "number"},
			{Name: "cancel-time", Type: "number"},
			{Name: "flash-time", Type: "number"},
		}},
		{Name: "set-multi-chassis-id", HighRisk: false, Input: []RPCInputLeaf{
			{Name: "current-chassis-id", Type: "number"},
			{Name: "next-chassis-id", Type: "number"},
		}},
		{Name: "set-next-system-mode", HighRisk: false, Input: []RPCInputLeaf{
			{Name: "next-system-mode", Type: "enum"},
		}},
		{Name: "set-next-work-mode", HighRisk: false, Input: []RPCInputLeaf{
			{Name: "next-work-mode", Type: "enum", Mandatory: true},
		}},
		{Name: "set-npu-led-flash", HighRisk: false, Input: []RPCInputLeaf{
			{Name: "alarm-status-time", Type: "number"},
			{Name: "board-position", Type: "leafref", LeafRef: "/devm:devm/devm:lpu-boards/devm:lpu-board/devm:position", Mandatory: true},
			{Name: "cancel-time", Type: "number"},
			{Name: "flash-time", Type: "number"},
		}},
		{Name: "set-nv-laser-turn", HighRisk: false, Input: []RPCInputLeaf{
			{Name: "if-name", Type: "leafref", LeafRef: "/ifm:ifm/ifm:interfaces/ifm:interface/ifm:name"},
			{Name: "laser-shutdown", Type: "enum"},
			{Name: "laser-test-time", Type: "number"},
		}},
		{Name: "set-slave-default", HighRisk: false, Input: []RPCInputLeaf{
			{Name: "chassis-id", Type: "string"},
		}},
		{Name: "set-slot-led-flash", HighRisk: false, Input: []RPCInputLeaf{
			{Name: "alarm-status-time", Type: "number"},
			{Name: "board-position", Type: "leafref", LeafRef: "/devm:devm/devm:mpu-boards/devm:mpu-board/devm:position", Mandatory: true},
			{Name: "cancel-time", Type: "number"},
			{Name: "flash-time", Type: "number"},
		}},
		{Name: "set-split-resume", HighRisk: false, Input: []RPCInputLeaf{
			{Name: "split-resume", Type: "enum", Mandatory: true},
		}},
		{Name: "set-usb-uart-stat", HighRisk: false, Input: []RPCInputLeaf{
			{Name: "usb-uart-status", Type: "enum"},
		}},
		{Name: "set-vsu-service-type", HighRisk: false, Input: []RPCInputLeaf{
			{Name: "position", Type: "string", Mandatory: true},
			{Name: "service-type", Type: "enum", Mandatory: true},
		}},
		{Name: "sysmac-load", HighRisk: false, Input: []RPCInputLeaf{
			{Name: "chassis-id", Type: "number"},
			{Name: "slot-id", Type: "string", Mandatory: true},
			{Name: "sysmac-file", Type: "string", Mandatory: true},
		}},
	},
	"evpn": {
		{Name: "reset-mac-address", HighRisk: false, Input: []RPCInputLeaf{
			{Name: "bd-id", Type: "number"},
			{Name: "mac-address", Type: "string", Pattern: "[0-9a-f]{4}(-[0-9a-f]{4}){2}"},
			{Name: "name", Type: "string"},
		}},
		{Name: "reset-mac-duplication", HighRisk: false, Input: []RPCInputLeaf{
			{Name: "bd-id", Type: "number"},
			{Name: "name", Type: "string"},
		}},
		{Name: "reset-mac-instance", HighRisk: false, Input: []RPCInputLeaf{
			{Name: "name", Type: "string"},
		}},
	},
	"ftpc": {
		{Name: "ftpc-transfer-file", HighRisk: false, Input: []RPCInputLeaf{
			{Name: "command-type", Type: "enum"},
			{Name: "ipv6-vpn-name", Type: "leafref", LeafRef: "/ni:network-instance/ni:instances/ni:instance/ni:name"},
			{Name: "is-public-net", Type: "boolean"},
			{Name: "local-file-name", Type: "string"},
			{Name: "password", Type: "string", Mandatory: true},
			{Name: "remote-extension", Type: "string"},
			{Name: "remote-file-name", Type: "string"},
			{Name: "server-ipv4-address", Type: "string"},
			{Name: "server-ipv6-address", Type: "string"},
			{Name: "server-port", Type: "number"},
			{Name: "source-interface-name", Type: "string"},
			{Name: "source-ipv4-address", Type: "string", Pattern: "(([0-9]|[1-9][0-9]|1[0-9][0-9]|2[0-4][0-9]|25[0-5])\\.){3}([0-9]|[1-9][0-9]|1[0-9][0-9]|2[0-4][0-9]|25[0-5])(%[\\p{N}\\p{L}]+)?"},
			{Name: "source-ipv6-address", Type: "string", Pattern: "((:|[0-9a-fA-F]{0,4}):)([0-9a-fA-F]{0,4}:){0,5}((([0-9a-fA-F]{0,4}:)?(:|[0-9a-fA-F]{0,4}))|(((25[0-5]|2[0-4][0-9]|[01]?[0-9]?[0-9])\\.){3}(25[0-5]|2[0-4][0-9]|[01]?[0-9]?[0-9])))(%[\\p{N}\\p{L}]+)?"},
			{Name: "user-name", Type: "string", Mandatory: true},
			{Name: "vpn-name", Type: "leafref", LeafRef: "/ni:network-instance/ni:instances/ni:instance/ni:name"},
		}},
	},
	"ifm": {
		{Name: "reset-if-control-flap-counts", HighRisk: false, Input: []RPCInputLeaf{
			{Name: "if-name", Type: "leafref", LeafRef: "/ifm:ifm/ifm:interfaces/ifm:interface/ifm:name", Mandatory: true},
		}},
		{Name: "reset-if-control-flap-penalty", HighRisk: false, Input: []RPCInputLeaf{
			{Name: "if-name", Type: "leafref", LeafRef: "/ifm:ifm/ifm:interfaces/ifm:interface/ifm:name", Mandatory: true},
		}},
		{Name: "reset-if-counters-all", HighRisk: false, Input: []RPCInputLeaf{
			{Name: "all-if", Type: "boolean", Mandatory: true},
		}},
		{Name: "reset-if-counters-by-name", HighRisk: false, Input: []RPCInputLeaf{
			{Name: "if-name", Type: "leafref", LeafRef: "/ifm:ifm/ifm:interfaces/ifm:interface/ifm:name", Mandatory: true},
		}},
		{Name: "reset-if-counters-by-type", HighRisk: false, Input: []RPCInputLeaf{
			{Name: "if-type", Type: "enum", Mandatory: true},
		}},
		{Name: "reset-if-mib-counters-all", HighRisk: false, Input: []RPCInputLeaf{
			{Name: "all-if", Type: "boolean", Mandatory: true},
		}},
		{Name: "reset-if-mib-counters-by-name", HighRisk: false, Input: []RPCInputLeaf{
			{Name: "if-name", Type: "leafref", LeafRef: "/ifm:ifm/ifm:interfaces/ifm:interface/ifm:name", Mandatory: true},
		}},
		{Name: "reset-if-mib-counters-by-type", HighRisk: false, Input: []RPCInputLeaf{
			{Name: "if-type", Type: "enum", Mandatory: true},
		}},
		{Name: "reset-remote-if-counters", HighRisk: false, Input: []RPCInputLeaf{
			{Name: "if-name", Type: "leafref", LeafRef: "/ifm:ifm/ifm:interfaces/ifm:interface/ifm:name", Mandatory: true},
		}},
		{Name: "restart-if", HighRisk: true, Input: []RPCInputLeaf{
			{Name: "if-name", Type: "leafref", LeafRef: "/ifm:ifm/ifm:interfaces/ifm:interface/ifm:name", Mandatory: true},
		}},
	},
	"ifm-trunk": {
		{Name: "trunk-switch", HighRisk: true, Input: []RPCInputLeaf{
			{Name: "if-name", Type: "leafref", LeafRef: "/ifm:ifm/ifm:interfaces/ifm:interface/ifm:name", Mandatory: true},
		}},
	},
	"license": {
		{Name: "license-active", HighRisk: false, Input: []RPCInputLeaf{
			{Name: "filename", Type: "string", Mandatory: true},
		}},
		{Name: "license-assign", HighRisk: false, Input: []RPCInputLeaf{
			{Name: "item-name", Type: "string"},
			{Name: "item-num", Type: "number"},
		}},
		{Name: "license-delete", HighRisk: true, Input: []RPCInputLeaf{
			{Name: "filename", Type: "string", Mandatory: true},
		}},
		{Name: "license-emergency", HighRisk: false},
		{Name: "license-export", HighRisk: false, Input: []RPCInputLeaf{
			{Name: "filename", Type: "string", Mandatory: true},
		}},
		{Name: "license-revoke", HighRisk: false},
		{Name: "license-revoke-chassis", HighRisk: false, Input: []RPCInputLeaf{
			{Name: "chassis-id", Type: "string"},
		}},
		{Name: "license-switch-mode", HighRisk: true, Input: []RPCInputLeaf{
			{Name: "license-mode", Type: "enum"},
		}},
		{Name: "license-trial", HighRisk: false, Input: []RPCInputLeaf{
			{Name: "trial-switch", Type: "boolean", Mandatory: true},
		}},
		{Name: "license-verify", HighRisk: false, Input: []RPCInputLeaf{
			{Name: "filename", Type: "string", Mandatory: true},
		}},
		{Name: "startup-paf", HighRisk: false, Input: []RPCInputLeaf{
			{Name: "filename", Type: "string", Mandatory: true},
		}},
	},
	"macsec": {
		{Name: "reset-macsec-statistics", HighRisk: false, Input: []RPCInputLeaf{
			{Name: "interface-name", Type: "leafref", LeafRef: "/ifm:ifm/ifm:interfaces/ifm:interface/ifm:name"},
		}},
		{Name: "reset-mka-statistics", HighRisk: false, Input: []RPCInputLeaf{
			{Name: "interface-name", Type: "leafref", LeafRef: "/ifm:ifm/ifm:interfaces/ifm:interface/ifm:name"},
		}},
	},
	"nqa": {
		{Name: "test-instance-execution", HighRisk: false, Input: []RPCInputLeaf{
			{Name: "admin-name", Type: "leafref", LeafRef: "/nqa/instances/instance/admin-name", Mandatory: true},
			{Name: "test-name", Type: "leafref", LeafRef: "/nqa/instances/instance/test-name", Mandatory: true},
		}},
	},
	"openflow-agent": {
		{Name: "reset-all-sessions", HighRisk: false},
		{Name: "reset-all-statistics", HighRisk: false},
	},
	"qos": {
		{Name: "reset-fabric-queue-multicast-statistics", HighRisk: false, Input: []RPCInputLeaf{
			{Name: "slot-id", Type: "string", Mandatory: true, Pattern: "(c[cl]c\\d+/)?\\d+"},
		}},
		{Name: "reset-fabric-queue-unicast-statistics", HighRisk: false, Input: []RPCInputLeaf{
			{Name: "destination-slot-id", Type: "string", Pattern: "(c[cl]c\\d+/)?\\d+"},
			{Name: "source-slot-id", Type: "string", Mandatory: true, Pattern: "(c[cl]c\\d+/)?\\d+"},
		}},
		{Name: "reset-global-policy-statistics", HighRisk: false, Input: []RPCInputLeaf{
			{Name: "direction", Type: "enum", Mandatory: true},
			{Name: "policy-name", Type: "string", Mandatory: true},
			{Name: "slot-id", Type: "string"},
		}},
		{Name: "reset-interface-buffer-usage-statistics", HighRisk: false, Input: []RPCInputLeaf{
			{Name: "interface-name", Type: "string"},
			{Name: "slot-id", Type: "string", Pattern: "(c[cl]c\\d+/)?\\d+"},
		}},
		{Name: "reset-interface-car-statistics", HighRisk: false, Input: []RPCInputLeaf{
			{Name: "ce-vid", Type: "number"},
			{Name: "direction", Type: "enum", Mandatory: true},
			{Name: "interface-name", Type: "string", Mandatory: true},
			{Name: "vid", Type: "number"},
			{Name: "vlan-id", Type: "number"},
		}},
		{Name: "reset-interface-default-flow-queue-statistics", HighRisk: false, Input: []RPCInputLeaf{
			{Name: "interface-name", Type: "string", Mandatory: true},
		}},
		{Name: "reset-interface-ecn-statistics", HighRisk: false, Input: []RPCInputLeaf{
			{Name: "interface-name", Type: "string"},
		}},
		{Name: "reset-interface-hard-pipe-statistics", HighRisk: false, Input: []RPCInputLeaf{
			{Name: "interface-name", Type: "string", Mandatory: true},
		}},
		{Name: "reset-interface-lv-hard-pipe-statistics", HighRisk: false, Input: []RPCInputLeaf{
			{Name: "interface-name", Type: "string", Mandatory: true},
		}},
		{Name: "reset-interface-port-queue-statistics", HighRisk: false, Input: []RPCInputLeaf{
			{Name: "default", Type: "string"},
			{Name: "interface-name", Type: "leafref", LeafRef: "/ifm:ifm/ifm:interfaces/ifm:interface/ifm:name"},
			{Name: "on-board", Type: "string"},
			{Name: "service-class", Type: "enum"},
		}},
		{Name: "reset-interface-profile-statistics", HighRisk: false, Input: []RPCInputLeaf{
			{Name: "direction", Type: "enum", Mandatory: true},
			{Name: "interface-name", Type: "string", Mandatory: true},
			{Name: "pe-vlan-id", Type: "number", Mandatory: true},
			{Name: "vlan-id", Type: "number", Mandatory: true},
		}},
		{Name: "reset-interface-sub-port-queue-statistics", HighRisk: false, Input: []RPCInputLeaf{
			{Name: "interface-name", Type: "leafref", LeafRef: "/ifm:ifm/ifm:interfaces/ifm:interface/ifm:name", Mandatory: true},
		}},
		{Name: "reset-interface-traffic-policy-statistics", HighRisk: false, Input: []RPCInputLeaf{
			{Name: "direction", Type: "enum", Mandatory: true},
			{Name: "interface-name", Type: "leafref", LeafRef: "/ifm:ifm/ifm:interfaces/ifm:interface/ifm:name", Mandatory: true},
			{Name: "pe-vlan-id", Type: "number", Mandatory: true},
			{Name: "vlan-id", Type: "number", Mandatory: true},
		}},
		{Name: "reset-interface-user-group-queue-statistics", HighRisk: false, Input: []RPCInputLeaf{
			{Name: "ce-vlan-id", Type: "number"},
			{Name: "direction", Type: "enum", Mandatory: true},
			{Name: "interface-name", Type: "string", Mandatory: true},
			{Name: "pe-vlan-id", Type: "number"},
			{Name: "vlan-id", Type: "number"},
		}},
		{Name: "reset-interface-user-queue-statistics", HighRisk: false, Input: []RPCInputLeaf{
			{Name: "direction", Type: "enum", Mandatory: true},
			{Name: "interface-name", Type: "string", Mandatory: true},
		}},
		{Name: "reset-mpls-te-statistics", HighRisk: false, Input: []RPCInputLeaf{
			{Name: "direction", Type: "enum", Mandatory: true},
			{Name: "interface-name", Type: "string", Mandatory: true},
		}},
		{Name: "reset-queue-statistics", HighRisk: false, Input: []RPCInputLeaf{
			{Name: "interface-name", Type: "leafref", LeafRef: "/ifm:ifm/ifm:interfaces/ifm:interface/ifm:name"},
			{Name: "service-class", Type: "enum"},
			{Name: "slot-id", Type: "string", Pattern: "(c[cl]c\\d+/)?\\d+"},
		}},
		{Name: "reset-slot-port-queue-statistics", HighRisk: false, Input: []RPCInputLeaf{
			{Name: "service-class", Type: "enum"},
			{Name: "slot-id", Type: "string", Mandatory: true, Pattern: "(c[cl]c\\d+/)?\\d+"},
		}},
		{Name: "reset-user-group-queue-statistics", HighRisk: false, Input: []RPCInputLeaf{
			{Name: "direction", Type: "enum", Mandatory: true},
			{Name: "slot-id", Type: "string"},
			{Name: "user-group-queue-name", Type: "leafref", LeafRef: "/qos:qos/qos:queue-scheduler-template/qos:user-group-queues/qos:user-group-queue/qos:name", Mandatory: true},
		}},
		{Name: "reset-user-informations", HighRisk: false, Input: []RPCInputLeaf{
			{Name: "direction", Type: "enum", Mandatory: true},
			{Name: "id", Type: "number", Mandatory: true},
		}},
		{Name: "reset-vlan-traffic-policy-statistics", HighRisk: false, Input: []RPCInputLeaf{
			{Name: "direction", Type: "enum"},
			{Name: "policy-name", Type: "leafref", LeafRef: "/qos:qos/qos:classifier-template/qos:traffic-policys/qos:traffic-policy/qos:name"},
			{Name: "vlan-id", Type: "number"},
		}},
		{Name: "reset-vpn-traffic-policy-statistics", HighRisk: false, Input: []RPCInputLeaf{
			{Name: "direction", Type: "enum"},
			{Name: "policy-name", Type: "leafref", LeafRef: "/qos:qos/qos:classifier-template/qos:traffic-policys/qos:traffic-policy/qos:name"},
			{Name: "vpn-instance", Type: "leafref", LeafRef: "/ni:network-instance/ni:instances/ni:instance/ni:name"},
		}},
	},
	"sflow": {
		{Name: "reset-interface-statistics", HighRisk: false, Input: []RPCInputLeaf{
			{Name: "interface-name", Type: "leafref", LeafRef: "/ifm:ifm/ifm:interfaces/ifm:interface/ifm:name", Mandatory: true},
			{Name: "slot-id", Type: "leafref", LeafRef: "/devm:devm/devm:lpu-boards/devm:lpu-board/devm:position"},
		}},
		{Name: "reset-slot-statistics", HighRisk: false, Input: []RPCInputLeaf{
			{Name: "slot-id", Type: "leafref", LeafRef: "/devm:devm/devm:lpu-boards/devm:lpu-board/devm:position", Mandatory: true},
		}},
	},
	"snmp": {
		{Name: "activate-users", HighRisk: false},
	},
	"unicast-forward": {
		{Name: "reset-na-anti-attack-statistic", HighRisk: false, Input: []RPCInputLeaf{
			{Name: "slot-id", Type: "string", Mandatory: true},
		}},
	},
	"vlan": {
		{Name: "reset-vlan-statistics", HighRisk: false, Input: []RPCInputLeaf{
			{Name: "vlan-id", Type: "number", Mandatory: true},
		}},
	},
}
