// Code generated by tools/tasknamegen. DO NOT EDIT.
//
// Maps module root-container names to the module-level `task-name`
// extension value (task domain) — drives /yang/modules `category` (BR-01).
package yangschema

// TaskNames maps a module's root container name to its task domain.
var TaskNames = map[string]string{
	"ifm":    "interface-mgr",
	"system": "system",
	"vlan":   "vlan",
}
