// Code generated by tools/tasknamegen. DO NOT EDIT.
//
// Maps module root-container names to the module-level `task-name`
// extension value (task domain) — drives /yang/modules `category` (BR-01).
package yangschema

// BusinessTaskNames maps a module's root container name to its task domain.
var BusinessTaskNames = map[string]string{
	"business-vlan-service": "business-network",
}
