// Command tasknamegen generates a Go map from module root-container names to
// the module-level vendor `task-name` extension value (task domain, BR-01).
//
// Module-level extensions do NOT survive into the ygot-embedded runtime schema
// (verified empirically: a full SchemaTree scan finds zero), so this runs at
// build time against the yang-models submodule — like the ygot generator — and
// the output is committed. Runtime keeps zero submodule dependency.
package main

import (
	"flag"
	"fmt"
	"go/format"
	"log"
	"os"
	"sort"
	"strings"

	"github.com/openconfig/goyang/pkg/yang"
)

func main() {
	path := flag.String("path", "", "directory containing the .yang modules")
	modules := flag.String("modules", "", "comma-separated module names to scan")
	output := flag.String("output", "taskname.gen.go", "output file")
	pkg := flag.String("package", "huawei", "package name for the generated file")
	flag.Parse()
	if *path == "" || *modules == "" {
		log.Fatal("tasknamegen: -path and -modules are required")
	}

	names, err := extractTaskNames(*path, strings.Split(*modules, ","))
	if err != nil {
		log.Fatalf("tasknamegen: %v", err)
	}
	src, err := renderSource(*pkg, names)
	if err != nil {
		log.Fatalf("tasknamegen: %v", err)
	}
	if err := os.WriteFile(*output, []byte(src), 0o644); err != nil {
		log.Fatalf("tasknamegen: %v", err)
	}
	log.Printf("tasknamegen: wrote %s (%d entries)", *output, len(names))
}

// extractTaskNames parses the named modules from dir and maps each module's
// top-level data container name (the key /yang/modules serves as module `name`)
// to its module-level `task-name` extension argument. Modules without the
// extension contribute nothing (callers omit `category`, R08).
func extractTaskNames(dir string, modules []string) (map[string]string, error) {
	ms := yang.NewModules()
	ms.AddPath(dir)
	for _, m := range modules {
		if err := ms.Read(strings.TrimSpace(m)); err != nil {
			return nil, fmt.Errorf("read %s: %w", m, err)
		}
	}
	if errs := ms.Process(); len(errs) > 0 {
		return nil, fmt.Errorf("process: %v", errs[0])
	}

	out := map[string]string{}
	for _, m := range modules {
		mod, ok := ms.Modules[strings.TrimSpace(m)]
		if !ok {
			return nil, fmt.Errorf("module %s not found after parse", m)
		}
		task := moduleTaskName(mod)
		if task == "" {
			continue
		}
		e := yang.ToEntry(mod)
		if e == nil {
			continue
		}
		for name, child := range e.Dir {
			// Only data containers/lists — RPC entries also appear in Dir but are
			// never served as modules by /yang/modules.
			if child.RPC != nil || !(child.IsContainer() || child.IsList()) {
				continue
			}
			out[name] = task
		}
	}
	return out, nil
}

// moduleTaskName returns the module-level `task-name` extension argument, ""
// if absent. Matching is prefix-agnostic (import aliases vary), same rule as
// the runtime extension consumers (BR-07).
func moduleTaskName(mod *yang.Module) string {
	for _, x := range mod.Exts() {
		if x == nil {
			continue
		}
		kw := x.Keyword
		if i := strings.LastIndex(kw, ":"); i >= 0 {
			kw = kw[i+1:]
		}
		if kw == "task-name" {
			return strings.Trim(strings.TrimSpace(x.Argument), `"`)
		}
	}
	return ""
}

// renderSource renders the generated Go file, sorted for deterministic output.
func renderSource(pkg string, names map[string]string) (string, error) {
	keys := make([]string, 0, len(names))
	for k := range names {
		keys = append(keys, k)
	}
	sort.Strings(keys)

	var b strings.Builder
	b.WriteString("// Code generated by tools/tasknamegen. DO NOT EDIT.\n")
	b.WriteString("//\n// Maps module root-container names to the module-level `task-name`\n")
	b.WriteString("// extension value (task domain) — drives /yang/modules `category` (BR-01).\n")
	fmt.Fprintf(&b, "package %s\n\n", pkg)
	b.WriteString("// TaskNames maps a module's root container name to its task domain.\n")
	b.WriteString("var TaskNames = map[string]string{\n")
	for _, k := range keys {
		fmt.Fprintf(&b, "\t%q: %q,\n", k, names[k])
	}
	b.WriteString("}\n")

	src, err := format.Source([]byte(b.String()))
	if err != nil {
		return "", fmt.Errorf("gofmt: %w", err)
	}
	return string(src), nil
}
