package main

import (
	"os"
	"path/filepath"
	"testing"
)

func TestFixSource(t *testing.T) {
	tests := []struct {
		name string
		in   string
		want string
	}{
		{
			name: "枚举标识符 | 替换为 _OR_（const 声明）",
			in:   "\tHuaweiIfm_PortType_50|100GE E_HuaweiIfm_PortType = 102\n",
			want: "\tHuaweiIfm_PortType_50_OR_100GE E_HuaweiIfm_PortType = 102\n",
		},
		{
			name: "FlexE 变体标识符",
			in:   "\tHuaweiIfm_PortType_FlexE_50|100G E_HuaweiIfm_PortType = 103\n",
			want: "\tHuaweiIfm_PortType_FlexE_50_OR_100G E_HuaweiIfm_PortType = 103\n",
		},
		{
			name: "注释中标识符替换但 YANG 原值保留",
			in:   "// HuaweiIfm_PortType_50|100GE corresponds to the value 50|100GE of HuaweiIfm_PortType\n",
			want: "// HuaweiIfm_PortType_50_OR_100GE corresponds to the value 50|100GE of HuaweiIfm_PortType\n",
		},
		{
			name: "YANG 原值字符串映射不动",
			in:   "\t\t102: {Name: \"50|100GE\"},\n",
			want: "\t\t102: {Name: \"50|100GE\"},\n",
		},
		{
			name: "非 Huawei 厂商前缀同样修复（泛化）",
			in:   "\tCiscoFoo_Speed_10|25G E_CiscoFoo_Speed = 7\n",
			want: "\tCiscoFoo_Speed_10_OR_25G E_CiscoFoo_Speed = 7\n",
		},
		{
			name: "同一标识符多个 | 全部替换",
			in:   "\tVendorX_Mode_1|2|3 E_VendorX_Mode = 1\n",
			want: "\tVendorX_Mode_1_OR_2_OR_3 E_VendorX_Mode = 1\n",
		},
		{
			name: "头部机器路径规范化",
			in:   "This package was generated by /Users/leezesi/go/pkg/mod/github.com/openconfig/ygot@v0.34.0/genutil/names.go\n",
			want: "This package was generated by github.com/openconfig/ygot@v0.34.0/genutil/names.go\n",
		},
		{
			name: "头部已规范化时不动（幂等）",
			in:   "This package was generated by github.com/openconfig/ygot@v0.34.0/genutil/names.go\n",
			want: "This package was generated by github.com/openconfig/ygot@v0.34.0/genutil/names.go\n",
		},
		{
			name: "无匹配输入原样返回",
			in:   "type Foo struct {\n\tBar *string `path:\"bar\"`\n}\n",
			want: "type Foo struct {\n\tBar *string `path:\"bar\"`\n}\n",
		},
		{
			name: "空输入",
			in:   "",
			want: "",
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got := fixSource(tt.in)
			if got != tt.want {
				t.Errorf("fixSource() = %q, want %q", got, tt.want)
			}
			if again := fixSource(got); again != tt.want {
				t.Errorf("fixSource 不幂等: 第二次执行 = %q, want %q", again, tt.want)
			}
		})
	}
}

func TestFixFile(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "all.gen.go")
	in := "This package was generated by /root/go/pkg/mod/github.com/openconfig/ygot@v0.34.0/genutil/names.go\n" +
		"\tHuaweiIfm_PortType_50|100GE E_HuaweiIfm_PortType = 102\n" +
		"\t\t102: {Name: \"50|100GE\"},\n"
	want := "This package was generated by github.com/openconfig/ygot@v0.34.0/genutil/names.go\n" +
		"\tHuaweiIfm_PortType_50_OR_100GE E_HuaweiIfm_PortType = 102\n" +
		"\t\t102: {Name: \"50|100GE\"},\n"
	if err := os.WriteFile(path, []byte(in), 0644); err != nil {
		t.Fatal(err)
	}
	if err := fixFile(path); err != nil {
		t.Fatalf("fixFile() error = %v", err)
	}
	got, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	if string(got) != want {
		t.Errorf("fixFile() 内容 = %q, want %q", string(got), want)
	}
}

func TestFixFileMissing(t *testing.T) {
	if err := fixFile(filepath.Join(t.TempDir(), "nope.gen.go")); err == nil {
		t.Error("fixFile(不存在的文件) 应返回错误")
	}
}
