package main

import (
	"bytes"
	"compress/gzip"
	"encoding/json"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestFixSource(t *testing.T) {
	tests := []struct {
		name string
		in   string
		want string
	}{
		{
			name: "枚举标识符 | 替换为 _OR_（const 声明）",
			in:   "\tHuaweiIfm_PortType_50|100GE E_HuaweiIfm_PortType = 102\n",
			want: "\tHuaweiIfm_PortType_50_OR_100GE E_HuaweiIfm_PortType = 102\n",
		},
		{
			name: "FlexE 变体标识符",
			in:   "\tHuaweiIfm_PortType_FlexE_50|100G E_HuaweiIfm_PortType = 103\n",
			want: "\tHuaweiIfm_PortType_FlexE_50_OR_100G E_HuaweiIfm_PortType = 103\n",
		},
		{
			name: "注释中标识符替换但 YANG 原值保留",
			in:   "// HuaweiIfm_PortType_50|100GE corresponds to the value 50|100GE of HuaweiIfm_PortType\n",
			want: "// HuaweiIfm_PortType_50_OR_100GE corresponds to the value 50|100GE of HuaweiIfm_PortType\n",
		},
		{
			name: "YANG 原值字符串映射不动",
			in:   "\t\t102: {Name: \"50|100GE\"},\n",
			want: "\t\t102: {Name: \"50|100GE\"},\n",
		},
		{
			name: "非 Huawei 厂商前缀同样修复（泛化）",
			in:   "\tCiscoFoo_Speed_10|25G E_CiscoFoo_Speed = 7\n",
			want: "\tCiscoFoo_Speed_10_OR_25G E_CiscoFoo_Speed = 7\n",
		},
		{
			name: "同一标识符多个 | 全部替换",
			in:   "\tVendorX_Mode_1|2|3 E_VendorX_Mode = 1\n",
			want: "\tVendorX_Mode_1_OR_2_OR_3 E_VendorX_Mode = 1\n",
		},
		{
			name: "头部机器路径规范化",
			in:   "This package was generated by /Users/leezesi/go/pkg/mod/github.com/openconfig/ygot@v0.34.0/genutil/names.go\n",
			want: "This package was generated by github.com/openconfig/ygot@v0.34.0/genutil/names.go\n",
		},
		{
			name: "头部已规范化时不动（幂等）",
			in:   "This package was generated by github.com/openconfig/ygot@v0.34.0/genutil/names.go\n",
			want: "This package was generated by github.com/openconfig/ygot@v0.34.0/genutil/names.go\n",
		},
		{
			name: "无匹配输入原样返回",
			in:   "type Foo struct {\n\tBar *string `path:\"bar\"`\n}\n",
			want: "type Foo struct {\n\tBar *string `path:\"bar\"`\n}\n",
		},
		{
			name: "空输入",
			in:   "",
			want: "",
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got, err := fixSource(tt.in)
			if err != nil {
				t.Fatalf("fixSource() error = %v", err)
			}
			if got != tt.want {
				t.Errorf("fixSource() = %q, want %q", got, tt.want)
			}
			again, err := fixSource(got)
			if err != nil {
				t.Fatalf("fixSource() 二次 error = %v", err)
			}
			if again != tt.want {
				t.Errorf("fixSource 不幂等: 第二次执行 = %q, want %q", again, tt.want)
			}
		})
	}
}

// makeYSchemaBlock 用 jsonStr 构造一个 ygot 同款 ySchema gzip blob 声明块。
// 故意用非确定性无关的 gzip（默认级别）——genfix 会重压为确定性形式。
func makeYSchemaBlock(t *testing.T, jsonStr string) string {
	t.Helper()
	var buf bytes.Buffer
	w := gzip.NewWriter(&buf)
	if _, err := w.Write([]byte(jsonStr)); err != nil {
		t.Fatal(err)
	}
	if err := w.Close(); err != nil {
		t.Fatal(err)
	}
	return "\tySchema = []byte{\n" + emitHexBytes(buf.Bytes()) + "\n\t}"
}

// extractSchemaJSON 从 fixSource 处理后的块中取回 schema JSON（供语义断言）。
func extractSchemaJSON(t *testing.T, src string) []byte {
	t.Helper()
	m := ySchemaBlock.FindStringSubmatch(src)
	if m == nil {
		t.Fatalf("未找到 ySchema 块: %q", src)
	}
	raw, err := parseHexBytes(m[2])
	if err != nil {
		t.Fatal(err)
	}
	j, err := gunzip(raw)
	if err != nil {
		t.Fatal(err)
	}
	return j
}

func TestFixSchemaBlobDeterministic(t *testing.T) {
	// 同一 schema、Augmented 多种顺序 → genfix 后字节一致。用 5 个元素（含 3+）
	// 以暴露 decorate-sort 错位 bug（2 元素时会假性通过）。
	elems := []string{
		`{"Name":"aaa","Config":1}`, `{"Name":"bbb","Config":0}`,
		`{"Name":"ccc","Config":2}`, `{"Name":"ddd","Config":0}`,
		`{"Name":"eee","Config":1}`,
	}
	wrap := func(order []int) string {
		parts := make([]string, len(order))
		for i, o := range order {
			parts[i] = elems[o]
		}
		return `{"Name":"root","Dir":{"iface":{"Augmented":[` + strings.Join(parts, ",") + `]}}}`
	}
	orders := [][]int{{0, 1, 2, 3, 4}, {4, 3, 2, 1, 0}, {2, 0, 4, 1, 3}, {1, 4, 0, 3, 2}}
	var canonical string
	for i, ord := range orders {
		fixed, err := fixSource(makeYSchemaBlock(t, wrap(ord)))
		if err != nil {
			t.Fatalf("fixSource(order %v) error = %v", ord, err)
		}
		if i == 0 {
			canonical = fixed
		} else if fixed != canonical {
			t.Errorf("Augmented 顺序 %v 的 genfix 输出与基准不一致", ord)
		}
	}
}

func TestFixSchemaBlobSemanticEquiv(t *testing.T) {
	// 规范化后 schema 语义等价：键集合与值不变，仅 Augmented 排序。
	in := `{"Name":"root","Dir":{"iface":{"Augmented":[{"Name":"b"},{"Name":"a"}]}}}`
	fixed, err := fixSource(makeYSchemaBlock(t, in))
	if err != nil {
		t.Fatalf("fixSource error = %v", err)
	}
	var got map[string]interface{}
	if err := json.Unmarshal(extractSchemaJSON(t, fixed), &got); err != nil {
		t.Fatal(err)
	}
	aug := got["Dir"].(map[string]interface{})["iface"].(map[string]interface{})["Augmented"].([]interface{})
	names := []string{
		aug[0].(map[string]interface{})["Name"].(string),
		aug[1].(map[string]interface{})["Name"].(string),
	}
	if names[0] != "a" || names[1] != "b" {
		t.Errorf("Augmented 未按稳定序排序: got %v, want [a b]", names)
	}
}

func TestFixSchemaBlobPreservesNumbers(t *testing.T) {
	// UseNumber 保证大整数不被 float64 重格式化损坏。
	const big = "18446744073709551615" // max uint64
	in := `{"Name":"root","Big":` + big + `,"Config":0}`
	fixed, err := fixSource(makeYSchemaBlock(t, in))
	if err != nil {
		t.Fatalf("fixSource error = %v", err)
	}
	j := extractSchemaJSON(t, fixed)
	if !bytes.Contains(j, []byte(big)) {
		t.Errorf("大整数被损坏，规范化后 JSON = %s", j)
	}
}

func TestFixSchemaBlobIdempotent(t *testing.T) {
	in := `{"Name":"root","Dir":{"iface":{"Augmented":[{"Name":"b"},{"Name":"a"}]}}}`
	once, err := fixSource(makeYSchemaBlock(t, in))
	if err != nil {
		t.Fatalf("fixSource error = %v", err)
	}
	twice, err := fixSource(once)
	if err != nil {
		t.Fatalf("fixSource 二次 error = %v", err)
	}
	if once != twice {
		t.Errorf("schema 规范化不幂等\n一次=%q\n二次=%q", once, twice)
	}
}

func TestFixFile(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "all.gen.go")
	in := "This package was generated by /root/go/pkg/mod/github.com/openconfig/ygot@v0.34.0/genutil/names.go\n" +
		"\tHuaweiIfm_PortType_50|100GE E_HuaweiIfm_PortType = 102\n" +
		"\t\t102: {Name: \"50|100GE\"},\n"
	want := "This package was generated by github.com/openconfig/ygot@v0.34.0/genutil/names.go\n" +
		"\tHuaweiIfm_PortType_50_OR_100GE E_HuaweiIfm_PortType = 102\n" +
		"\t\t102: {Name: \"50|100GE\"},\n"
	if err := os.WriteFile(path, []byte(in), 0644); err != nil {
		t.Fatal(err)
	}
	if err := fixFile(path); err != nil {
		t.Fatalf("fixFile() error = %v", err)
	}
	got, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	if string(got) != want {
		t.Errorf("fixFile() 内容 = %q, want %q", string(got), want)
	}
}

func TestFixFileMissing(t *testing.T) {
	if err := fixFile(filepath.Join(t.TempDir(), "nope.gen.go")); err == nil {
		t.Error("fixFile(不存在的文件) 应返回错误")
	}
}

// —— 拆分文件集（-output_dir 布局）契约：genfix 逐文件安全、无需感知文件内容 ——

func TestFixFileNoSchemaNoop(t *testing.T) {
	// structs-N.go 类文件：无 ySchema blob、无枚举 |、头部已规范 → 原样保留。
	dir := t.TempDir()
	path := filepath.Join(dir, "structs-0.go")
	in := "// This package was generated by github.com/openconfig/ygot@v0.34.0/genutil/names.go\n" +
		"package huawei\n\ntype HuaweiVlan_Vlan struct {\n\tVlans *HuaweiVlan_Vlan_Vlans `path:\"vlans\"`\n}\n"
	if err := os.WriteFile(path, []byte(in), 0644); err != nil {
		t.Fatal(err)
	}
	if err := fixFile(path); err != nil {
		t.Fatalf("fixFile() error = %v", err)
	}
	got, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	if string(got) != in {
		t.Errorf("无 blob/枚举文件应 no-op\ngot  = %q\nwant = %q", string(got), in)
	}
}

func TestFixSchemaBlobStandaloneFile(t *testing.T) {
	// schema.go 类文件：blob 独占一文件、无 struct 上下文，ySchemaBlock 仍须定位并
	// 确定性规范化（design D4 显式锁定，spike 仅间接验证过）。
	dir := t.TempDir()
	path := filepath.Join(dir, "schema.go")
	blob := makeYSchemaBlock(t, `{"Name":"root","Dir":{"iface":{"Augmented":[{"Name":"b"},{"Name":"a"}]}}}`)
	in := "package huawei\n\nvar (\n" + blob + "\n)\n"
	if err := os.WriteFile(path, []byte(in), 0644); err != nil {
		t.Fatal(err)
	}
	if err := fixFile(path); err != nil {
		t.Fatalf("fixFile() error = %v", err)
	}
	got, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	if string(got) == in {
		t.Fatal("独立 schema.go 中的 blob 未被规范化（ySchemaBlock 未命中）")
	}
	var schema map[string]interface{}
	if err := json.Unmarshal(extractSchemaJSON(t, string(got)), &schema); err != nil {
		t.Fatalf("规范化后 blob 不可解压/解析: %v", err)
	}
	aug := schema["Dir"].(map[string]interface{})["iface"].(map[string]interface{})["Augmented"].([]interface{})
	if aug[0].(map[string]interface{})["Name"] != "a" {
		t.Errorf("独立文件中 Augmented 未确定性重排: %v", aug)
	}
}

func TestFixFileSetIdempotent(t *testing.T) {
	// 拆分布局全家福：structs-0/enum/enum_map/union/schema 各司其职，
	// 逐文件跑 genfix（同 main 的多入参循环）两轮，第二轮零变更。
	dir := t.TempDir()
	files := map[string]string{
		"structs-0.go": "package huawei\n\ntype HuaweiIfm_Ifm struct {\n\tInterfaces *HuaweiIfm_Ifm_Interfaces `path:\"interfaces\"`\n}\n",
		"enum.go":      "package huawei\n\nconst (\n\tHuaweiIfm_PortType_50|100GE E_HuaweiIfm_PortType = 102\n)\n",
		"enum_map.go":  "package huawei\n\nvar ΛEnum = map[string]map[int64]ygot.EnumDefinition{\n\t\"E_HuaweiIfm_PortType\": {\n\t\t102: {Name: \"50|100GE\"},\n\t},\n}\n",
		"union.go":     "package huawei\n\ntype HuaweiIfm_Union_String struct {\n\tString string\n}\n",
		"schema.go": "package huawei\n\nvar (\n" +
			makeYSchemaBlock(t, `{"Name":"root","Dir":{"a":{"Augmented":[{"Name":"y"},{"Name":"x"}]}}}`) + "\n)\n",
	}
	paths := make([]string, 0, len(files))
	for name, content := range files {
		p := filepath.Join(dir, name)
		if err := os.WriteFile(p, []byte(content), 0644); err != nil {
			t.Fatal(err)
		}
		paths = append(paths, p)
	}
	round := func() map[string]string {
		out := map[string]string{}
		for _, p := range paths {
			if err := fixFile(p); err != nil {
				t.Fatalf("fixFile(%s) error = %v", p, err)
			}
			b, err := os.ReadFile(p)
			if err != nil {
				t.Fatal(err)
			}
			out[filepath.Base(p)] = string(b)
		}
		return out
	}
	first := round()
	// 逐文件职责断言
	if first["structs-0.go"] != files["structs-0.go"] {
		t.Error("structs-0.go 应 no-op")
	}
	if !strings.Contains(first["enum.go"], "PortType_50_OR_100GE") {
		t.Errorf("enum.go 枚举标识符未修复: %q", first["enum.go"])
	}
	if !strings.Contains(first["enum_map.go"], `{Name: "50|100GE"}`) {
		t.Errorf("enum_map.go 的 YANG 原值映射串被误改: %q", first["enum_map.go"])
	}
	if first["union.go"] != files["union.go"] {
		t.Error("union.go 应 no-op")
	}
	if first["schema.go"] == files["schema.go"] {
		t.Error("schema.go blob 应被确定性重排")
	}
	// 幂等：第二轮零变更
	second := round()
	for name := range files {
		if second[name] != first[name] {
			t.Errorf("%s 不幂等：第二轮内容发生变化", name)
		}
	}
}
