// Command genfix 是 ygot 生成物的跨平台后处理器（替代平台方言 sed）：
//  1. 修复生成的枚举标识符中的非法字符 `|`（如 PortType_50|100GE →
//     PortType_50_OR_100GE），仅作用于标识符，YANG 原值字符串映射保持原样；
//  2. 规范化文件头部的生成器机器绝对路径，保证生成物跨机器字节一致
//     （CI regen-and-diff 门禁的前提）。
//
// 用法: go run ./tools/genfix <file> [<file>...]
package main

import (
	"fmt"
	"os"
	"regexp"
)

var (
	// 枚举标识符内的 `|`：左侧须为「大写开头且含 _ 的标识符片段」，
	// 这样不会命中 YANG 原值字符串（如 "50|100GE"，左侧 50 不满足）。
	enumBar = regexp.MustCompile(`([A-Z]\w*_\w*)\|(\w+)`)
	// 生成器绝对路径头部（含机器特定的 go mod cache 前缀）。
	genHeader = regexp.MustCompile(`(This package was generated by )\S+/(github\.com/openconfig/ygot@\S+)`)
)

// fixSource 对生成物源码做全部修复，幂等。
func fixSource(src string) string {
	for {
		out := enumBar.ReplaceAllString(src, "${1}_OR_${2}")
		if out == src {
			break
		}
		src = out
	}
	return genHeader.ReplaceAllString(src, "${1}${2}")
}

// fixFile 就地修复单个文件，内容无变化时不重写。
func fixFile(path string) error {
	content, err := os.ReadFile(path)
	if err != nil {
		return fmt.Errorf("genfix: %w", err)
	}
	fixed := fixSource(string(content))
	if fixed == string(content) {
		return nil
	}
	if err := os.WriteFile(path, []byte(fixed), 0644); err != nil {
		return fmt.Errorf("genfix: %w", err)
	}
	return nil
}

func main() {
	if len(os.Args) < 2 {
		fmt.Fprintln(os.Stderr, "usage: genfix <file> [<file>...]")
		os.Exit(1)
	}
	for _, path := range os.Args[1:] {
		if err := fixFile(path); err != nil {
			fmt.Fprintln(os.Stderr, err)
			os.Exit(1)
		}
	}
}
