// Command genfix 是 ygot 生成物的跨平台后处理器（替代平台方言 sed），做三类
// 幂等、机器无关的后处理，以满足 yang-codegen-pipeline CG-01「同一仓库状态下
// 重复执行输出字节一致」与 CG-02：
//  1. 修复生成的枚举标识符中的非法字符 `|`（如 PortType_50|100GE →
//     PortType_50_OR_100GE），仅作用于标识符，YANG 原值字符串映射保持原样；
//  2. 规范化文件头部的生成器机器绝对路径，保证生成物跨机器字节一致；
//  3. 确定性 schema 规范化：ygot 内嵌的 gzip schema blob（var ySchema）序列化了
//     yang.Entry 的无序集合数组（首要为各节点 Augmented——同一目标被多模块 augment
//     时，goyang 以非确定 map 迭代序应用，致数组元素顺序逐次不同、gzip 字节漂移）。
//     本步解压 blob → 对无序集合数组与对象键做确定性重排（保持 schema 语义等价）
//     → 以固定参数重压 → 回填，使 blob 字节在重复生成间稳定。
//
// 用法: go run ./tools/genfix <file> [<file>...]
package main

import (
	"bytes"
	"compress/gzip"
	"encoding/json"
	"fmt"
	"io"
	"os"
	"regexp"
	"sort"
	"strconv"
	"strings"
)

var (
	// 枚举标识符内的 `|`：左侧须为「大写开头且含 _ 的标识符片段」，
	// 这样不会命中 YANG 原值字符串（如 "50|100GE"，左侧 50 不满足）。
	enumBar = regexp.MustCompile(`([A-Z]\w*_\w*)\|(\w+)`)
	// 生成器绝对路径头部（含机器特定的 go mod cache 前缀）。
	genHeader = regexp.MustCompile(`(This package was generated by )\S+/(github\.com/openconfig/ygot@\S+)`)
	// ygot 内嵌 gzip schema：`\tySchema = []byte{\n\t\t0x..,\n\t}`。
	ySchemaBlock = regexp.MustCompile(`(?s)(\tySchema = \[\]byte\{\n)(.*?)(\n\t\})`)
	hexByte      = regexp.MustCompile(`0x([0-9a-fA-F]{2})`)
)

// fixText 对生成物源码做正则类文本修复（枚举 | + 头部路径），幂等。
func fixText(src string) string {
	for {
		out := enumBar.ReplaceAllString(src, "${1}_OR_${2}")
		if out == src {
			break
		}
		src = out
	}
	return genHeader.ReplaceAllString(src, "${1}${2}")
}

// fixSchemaBlob 定位并确定性规范化 ySchema gzip blob；无 blob 时原样返回。
func fixSchemaBlob(src string) (string, error) {
	m := ySchemaBlock.FindStringSubmatch(src)
	if m == nil {
		return src, nil
	}
	raw, err := parseHexBytes(m[2])
	if err != nil {
		return "", fmt.Errorf("解析 ySchema 字节: %w", err)
	}
	jsonBytes, err := gunzip(raw)
	if err != nil {
		return "", fmt.Errorf("解压 ySchema: %w", err)
	}
	canon, err := canonicalizeSchemaJSON(jsonBytes)
	if err != nil {
		return "", fmt.Errorf("规范化 schema: %w", err)
	}
	gz, err := gzipDeterministic(canon)
	if err != nil {
		return "", fmt.Errorf("重压 schema: %w", err)
	}
	replacement := m[1] + emitHexBytes(gz) + m[3]
	return strings.Replace(src, m[0], replacement, 1), nil
}

// fixSource 依次做文本修复与 schema 规范化，幂等。
func fixSource(src string) (string, error) {
	return fixSchemaBlob(fixText(src))
}

func parseHexBytes(body string) ([]byte, error) {
	ms := hexByte.FindAllStringSubmatch(body, -1)
	out := make([]byte, len(ms))
	for i, m := range ms {
		v, err := strconv.ParseUint(m[1], 16, 8)
		if err != nil {
			return nil, err
		}
		out[i] = byte(v)
	}
	return out, nil
}

func gunzip(b []byte) ([]byte, error) {
	r, err := gzip.NewReader(bytes.NewReader(b))
	if err != nil {
		return nil, err
	}
	defer r.Close()
	return io.ReadAll(r)
}

// gzipDeterministic 以固定压缩级别 + 零值头部（ModTime=0、OS=255）压缩，
// 保证同一输入跨调用/跨机器字节一致。
func gzipDeterministic(b []byte) ([]byte, error) {
	var buf bytes.Buffer
	w, err := gzip.NewWriterLevel(&buf, gzip.BestCompression)
	if err != nil {
		return nil, err
	}
	if _, err := w.Write(b); err != nil {
		return nil, err
	}
	if err := w.Close(); err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}

// canonicalizeSchemaJSON 解析 schema JSON（UseNumber 保留数字字面量不重格式化），
// 对无序集合数组与对象键做确定性重排后重新序列化。json.Marshal 自动按键排序 map，
// 故对象键确定；无序数组（Augmented）显式排序。语义等价：GzipToSchema 按字段名/
// Dir map 查找，元素顺序不影响 schema 结构。
func canonicalizeSchemaJSON(jsonBytes []byte) ([]byte, error) {
	dec := json.NewDecoder(bytes.NewReader(jsonBytes))
	dec.UseNumber()
	var v interface{}
	if err := dec.Decode(&v); err != nil {
		return nil, err
	}
	sortUnorderedArrays(v)
	return json.Marshal(v)
}

// unorderedArrayKeys 是 yang.Entry 序列化中语义无序、可安全稳定排序的数组字段。
// 目前仅 Augmented（多模块 augment 同一目标的应用序，goyang 非确定）；如后续发现
// 其他非确定数组，在此登记（须确认语义无序，勿纳入 ordered-by-user/enum 值等有序构造）。
var unorderedArrayKeys = map[string]bool{"Augmented": true}

func sortUnorderedArrays(v interface{}) {
	switch t := v.(type) {
	case map[string]interface{}:
		for k, val := range t {
			sortUnorderedArrays(val)
			if unorderedArrayKeys[k] {
				if arr, ok := val.([]interface{}); ok {
					sortByCanonical(arr)
				}
			}
		}
	case []interface{}:
		for _, e := range t {
			sortUnorderedArrays(e)
		}
	}
}

// sortByCanonical 以元素的规范化 JSON（json.Marshal 已按键排序）为稳定序排序。
// 元素内嵌的无序数组须已先行排序（sortUnorderedArrays 深度优先保证）。
// 键与值须绑定同排（decorate-sort），不可用独立 keys 切片作比较器——否则元素
// 移位后比较器读到错位的键，排序既不正确也不确定。
func sortByCanonical(arr []interface{}) {
	type kv struct {
		key string
		val interface{}
	}
	pairs := make([]kv, len(arr))
	for i, e := range arr {
		b, _ := json.Marshal(e)
		pairs[i] = kv{string(b), e}
	}
	sort.SliceStable(pairs, func(i, j int) bool { return pairs[i].key < pairs[j].key })
	for i := range pairs {
		arr[i] = pairs[i].val
	}
}

// emitHexBytes 以 ygot 同款 16 字节/行格式回填（gofmt 后续规范化，此处确定即可）。
func emitHexBytes(b []byte) string {
	var sb strings.Builder
	for i, c := range b {
		if i%16 == 0 {
			sb.WriteString("\t\t")
		}
		fmt.Fprintf(&sb, "0x%02x,", c)
		if i%16 == 15 || i == len(b)-1 {
			sb.WriteByte('\n')
		} else {
			sb.WriteByte(' ')
		}
	}
	return strings.TrimRight(sb.String(), "\n")
}

// fixFile 就地修复单个文件，内容无变化时不重写。
func fixFile(path string) error {
	content, err := os.ReadFile(path)
	if err != nil {
		return fmt.Errorf("genfix: %w", err)
	}
	fixed, err := fixSource(string(content))
	if err != nil {
		return fmt.Errorf("genfix %s: %w", path, err)
	}
	if fixed == string(content) {
		return nil
	}
	if err := os.WriteFile(path, []byte(fixed), 0644); err != nil {
		return fmt.Errorf("genfix: %w", err)
	}
	return nil
}

func main() {
	if len(os.Args) < 2 {
		fmt.Fprintln(os.Stderr, "usage: genfix <file> [<file>...]")
		os.Exit(1)
	}
	for _, path := range os.Args[1:] {
		if err := fixFile(path); err != nil {
			fmt.Fprintln(os.Stderr, err)
			os.Exit(1)
		}
	}
}
